using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Adamantium.Engine.Generators;

/// <summary>
/// Emits a typed, compile-checked registry of a project's content resources so assets are loaded by a
/// const member instead of a hand-typed path: <c>Content.Load&lt;SceneData&gt;(SandboxAssets.Models.F15C.F_15C_Eagle_dae)</c>.
/// The registry is <c>{RootNamespace}.{Project}Assets</c> (namespace + class name both project-scoped, so two
/// projects never collide), with nested static classes mirroring folders and a <c>const string</c> per asset
/// holding its logical load name. The source format is appended to a member name only when two files in the
/// same folder would otherwise collide.
/// </summary>
[Generator]
public class AssetsGenerator : IIncrementalGenerator
{
    private static readonly HashSet<string> AssetExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        // models
        ".dae", ".obj", ".3ds", ".fbx",
        // textures
        ".png", ".jpg", ".jpeg", ".bmp", ".tga", ".gif", ".dds", ".ico",
        // fonts
        ".ttf", ".otf", ".woff", ".woff2"
    };

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assetPaths = context.AdditionalTextsProvider
            .Where(file => AssetExtensions.Contains(Path.GetExtension(file.Path)))
            .Select((file, _) => file.Path)
            .Collect();

        var source = assetPaths.Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(source, (spc, pair) =>
        {
            var (paths, config) = pair;
            if (paths.IsDefaultOrEmpty) return;

            config.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
            config.GlobalOptions.TryGetValue("build_property.MSBuildProjectName", out var projectName);
            config.GlobalOptions.TryGetValue("build_property.ProjectDir", out var projectDir);

            if (string.IsNullOrEmpty(rootNamespace) || string.IsNullOrEmpty(projectDir))
                return;

            var root = BuildTree(paths, projectDir);
            var className = Capitalize(Sanitize(LastSegment(projectName))) + "Assets";
            spc.AddSource("Assets.g.cs", SourceText.From(Emit(root, rootNamespace, className), Encoding.UTF8));
        });
    }

    private static FolderNode BuildTree(IEnumerable<string> paths, string projectDir)
    {
        var root = new FolderNode("");
        foreach (var path in paths)
        {
            var relative = ToRelative(path, projectDir);
            if (relative is null) continue;

            var segments = relative.Split('/');
            var node = root;
            for (var i = 0; i < segments.Length - 1; i++)
            {
                var folder = segments[i];
                if (!node.Children.TryGetValue(folder, out var child))
                {
                    child = new FolderNode(folder);
                    node.Children[folder] = child;
                }

                node = child;
            }

            var fileName = segments[segments.Length - 1];
            node.Files.Add((Path.GetFileNameWithoutExtension(fileName), Path.GetExtension(fileName), relative));
        }

        return root;
    }

    private static string Emit(FolderNode root, string rootNamespace, string className)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Compile-checked registry of this project's content resources.</summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        EmitBody(sb, root, className, 1);
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitBody(StringBuilder sb, FolderNode node, string containingClassName, int indent)
    {
        var pad = new string(' ', indent * 4);
        var used = new HashSet<string>(StringComparer.Ordinal) { containingClassName };

        // Nested folder classes first (reserve their names so members can't shadow them).
        var childClasses = node.Children.Values
            .Select(child => (name: Unique(used, Capitalize(Sanitize(child.RawName))), node: child))
            .OrderBy(c => c.name, StringComparer.Ordinal)
            .ToList();

        // Member name = file name; the format is appended only when the base name would clash with another
        // file in the folder or with the containing class (a member can't share its enclosing type's name).
        var members = node.Files
            .Select(file =>
            {
                var baseName = Capitalize(Sanitize(file.NameNoExt));
                var collides = baseName == containingClassName
                               || node.Files.Count(other => Capitalize(Sanitize(other.NameNoExt)) == baseName) > 1;
                var name = collides ? baseName + "_" + SanitizeExtension(file.Ext.TrimStart('.')) : baseName;
                return (name: Unique(used, name), value: file.RelativePath);
            })
            .OrderBy(m => m.name, StringComparer.Ordinal)
            .ToList();

        foreach (var member in members)
            sb.AppendLine($"{pad}public const string {member.name} = \"{member.value}\";");

        if (members.Count > 0 && childClasses.Count > 0)
            sb.AppendLine();

        for (var i = 0; i < childClasses.Count; i++)
        {
            sb.AppendLine($"{pad}public static class {childClasses[i].name}");
            sb.AppendLine($"{pad}{{");
            EmitBody(sb, childClasses[i].node, childClasses[i].name, indent + 1);
            sb.AppendLine($"{pad}}}");
            if (i < childClasses.Count - 1) sb.AppendLine();
        }
    }

    private static string ToRelative(string path, string projectDir)
    {
        var full = path.Replace('\\', '/');
        var root = projectDir.Replace('\\', '/').TrimEnd('/') + "/";
        if (!full.StartsWith(root, StringComparison.OrdinalIgnoreCase)) return null;
        return full.Substring(root.Length);
    }

    private static string LastSegment(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Project";
        var dot = name.LastIndexOf('.');
        return dot >= 0 && dot < name.Length - 1 ? name.Substring(dot + 1) : name;
    }

    private static string Unique(HashSet<string> used, string name)
    {
        var candidate = name;
        var suffix = 2;
        while (!used.Add(candidate))
            candidate = name + "_" + suffix++;
        return candidate;
    }

    private static string Sanitize(string name)
    {
        if (string.IsNullOrEmpty(name)) return "_";
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        var result = sb.ToString();
        if (char.IsDigit(result[0])) result = "_" + result;
        return result;
    }

    // Like Sanitize but for a trailing format suffix: keeps a leading digit (e.g. "3ds"), since it is appended
    // after an existing identifier and underscore, so "F_15C_Eagle_3ds" rather than "F_15C_Eagle__3ds".
    private static string SanitizeExtension(string ext)
    {
        if (string.IsNullOrEmpty(ext)) return "_";
        var sb = new StringBuilder(ext.Length);
        foreach (var ch in ext)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        return sb.ToString();
    }

    private static string Capitalize(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    private sealed class FolderNode
    {
        public FolderNode(string rawName) => RawName = rawName;

        public string RawName { get; }

        public SortedDictionary<string, FolderNode> Children { get; } = new(StringComparer.OrdinalIgnoreCase);

        public List<(string NameNoExt, string Ext, string RelativePath)> Files { get; } = [];
    }
}
