using Adamantium.Mathematics;
using Adamantium.MVVM;
using Adamantium.UI.Core;
using Adamantium.UI.Core.Media;

namespace Adamantium.Game.Sandbox.ViewModels;

/// <summary>Color Picker tab: an inline ColorPicker (SV square + hue/alpha bars + hex/RGBA fields) two-way bound to
/// <see cref="PickedColor"/>, which is also fed live into the THEME's accent - so dragging the picker recolours the accent
/// controls next to it (and everywhere) with no theme reload, a visible end-to-end demo.</summary>
[ViewModel]
public partial class ColorPickerViewModel : TabPageViewModel
{
    public ColorPickerViewModel() : base("Color Picker") { }

    /// <summary>The shared picked colour - bound two-way into the picker and pushed into the theme accent.</summary>
    [Bindable] private Color _pickedColor = new(0x3B, 0x82, 0xF6, 0xFF);

    // Generated by [Bindable]; runs after PickedColor changes. Push the (opaque) colour into the live theme accent, which
    // re-derives the accent ramp and re-colours every {ThemeResource Accent*} consumer instantly.
    partial void OnPickedColorChanged(Color value)
    {
        if (UIAppContext.Current?.ThemeManager?.CurrentTheme is { } theme)
        {
            theme.AccentColor = new SolidColorBrush(new Color(value.R, value.G, value.B, (byte)255));
        }
    }
}
