using System.Collections.ObjectModel;
using System.IO;
using Adamantium.MVVM;

namespace Adamantium.Game.Sandbox.ViewModels;

/// <summary>One node of the file-system demo tree: a file (leaf) or a directory. A directory is LAZY - it carries a single
/// placeholder child so the expander shows, and reads its real contents only when first expanded. <see cref="IsExpanded"/>
/// is a <c>[Bindable]</c> property (source-generated notification) bound two-way to the container via the tree's
/// ItemContainerStyle, and its generated <c>OnIsExpandedChanged</c> hook is what triggers the load - no hand-written INPC.
/// That laziness is what makes pointing the tree at a whole drive affordable, and a good stress test for virtualization.</summary>
[ViewModel]
public partial class TreeNode : AdamantiumViewModel
{
    private readonly string _path;
    private readonly bool _isDirectory;
    private bool _loaded;

    private TreeNode(string title, string path, bool isDirectory)
    {
        Title = title;
        _path = path;
        _isDirectory = isDirectory;
        // A directory starts with a placeholder so it shows an expander BEFORE its contents are read; the first expand
        // swaps it for the real children. A file is a leaf.
        if (isDirectory) Children.Add(new TreeNode("…", null, false));
    }

    /// <summary>The node's label (file or directory name; a drive root shows its path).</summary>
    public string Title { get; }

    /// <summary>The child nodes. For a lazy directory these are a placeholder until the first expand fills them in.</summary>
    public ObservableCollection<TreeNode> Children { get; } = [];

    /// <summary>Whether this branch is open - bound two-way to the container. The first open reads the directory (lazy load).</summary>
    [Bindable] private bool _isExpanded;

    // Generated by [Bindable]; runs after IsExpanded flips. Opening a directory the first time reads its contents.
    partial void OnIsExpandedChanged(bool value)
    {
        if (value) EnsureLoaded();
    }

    /// <summary>A directory node (starts collapsed + lazy). The label is the folder name, or the path for a drive root.</summary>
    public static TreeNode Directory(string path)
    {
        var name = Path.GetFileName(Path.TrimEndingDirectorySeparator(path));
        return new TreeNode(string.IsNullOrEmpty(name) ? path : name, path, true);
    }

    private static TreeNode File(string path) => new(Path.GetFileName(path), path, false);

    private void EnsureLoaded()
    {
        if (_loaded || !_isDirectory) return;
        _loaded = true;
        Children.Clear(); // drop the placeholder
        try
        {
            foreach (var dir in System.IO.Directory.EnumerateDirectories(_path)) Children.Add(Directory(dir));
            foreach (var file in System.IO.Directory.EnumerateFiles(_path)) Children.Add(File(file));
        }
        catch
        {
            // Access denied / removed / reparse loop - leave the branch empty rather than tear down the demo.
        }
    }

    public override string ToString() => Title;
}
