using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using Adamantium.MVVM;
using Adamantium.UI.Controls;

namespace Adamantium.Game.Sandbox.ViewModels;

/// <summary>Trees tab: a TreeView pointed at a REAL drive's file system, projected by a HierarchicalDataTemplate (the same
/// container seam the data-driven menus use) - nothing authored in markup. A DropDown picks the drive, another flips the
/// <see cref="SelectedMode"/> (Single / Multiple / Extended), and a <c>[Command]</c> re-reads the drive. Directories load
/// lazily on expand, so a whole drive is affordable - and doubles as a stress test for the coming virtualization.</summary>
[ViewModel]
public partial class TreesViewModel : TabPageViewModel
{
    /// <summary>The tree root(s) - the selected drive. The view binds TreeView.ItemsSource to it.</summary>
    public ObservableCollection<TreeNode> Nodes { get; } = [];

    /// <summary>The ready drives, for the drive DropDown.</summary>
    public string[] Drives { get; }

    /// <summary>The drive whose file system the tree shows - bound two-way to the drive DropDown.</summary>
    [Bindable] private string _selectedDrive;

    /// <summary>The choices in the selection-mode DropDown.</summary>
    public TreeViewSelectionMode[] SelectionModes { get; } = [TreeViewSelectionMode.Single, TreeViewSelectionMode.Multiple, TreeViewSelectionMode.Extended];

    /// <summary>The live selection mode - bound two-way to the DropDown and into TreeView.SelectionMode.</summary>
    [Bindable] private TreeViewSelectionMode _selectedMode = TreeViewSelectionMode.Single;

    public TreesViewModel() : base("Trees")
    {
        Drives = DriveInfo.GetDrives().Where(d => d.IsReady).Select(d => d.Name).ToArray();
        SelectedDrive = Drives.FirstOrDefault(); // fires OnSelectedDriveChanged -> LoadDrive
    }

    // Generated by [Bindable]; re-point the tree whenever the drive changes.
    partial void OnSelectedDriveChanged(string value) => LoadDrive();

    /// <summary>Re-read the current drive from scratch (generates RefreshCommand) - collapses back to a fresh root.</summary>
    [Command] private void Refresh() => LoadDrive();

    // Point the tree at the selected drive's root. Only the root node is created here; everything below loads lazily on
    // expand - see TreeNode.
    private void LoadDrive()
    {
        Nodes.Clear();
        if (!string.IsNullOrEmpty(SelectedDrive)) Nodes.Add(TreeNode.Directory(SelectedDrive));
    }
}
