<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adamantium.UI.Core\Adamantium.UI.Core.csproj" />
      <ProjectReference Include="..\Adamantium.Navigation\Adamantium.Navigation.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Adamantium.UI" />
        <InternalsVisibleTo Include="Adamantium.UITests" />
    </ItemGroup>

</Project>
