using System.Collections.Generic;

namespace Adamantium.Fonts.Common
{
    public static class FeatureInfos
    {
        private static readonly string cvFeatureDescription = "A font may have stylistic-variant glyphs for one or more characters where the variations for one character are not systematically related to those for other characters. Or, a variation may exist for a character and its casing pair (or related pre-composed characters), but not be applicable to other unrelated characters. In some usage scenarios, it may be necessary to provide the application with control over glyph variations for different Unicode characters individually.";

        private static readonly string ssFeatureDescription =
            "In addition to, or instead of, stylistic alternatives of individual glyphs (see 'salt' feature), some fonts may contain sets of stylistic variant glyphs corresponding to portions of the character set, e.g. multiple variants for lowercase letters in a Latin font. Glyphs in stylistic sets may be designed to harmonise visually, interract in particular ways, or otherwise work together. Examples of fonts including stylistic sets are Zapfino Linotype and Adobe’s Poetica. Individual features numbered sequentially with the tag name convention 'ss01', 'ss02', 'ss03'… 'ss20' provide a mechanism for glyphs in these sets to be associated via GSUB lookup indices to default forms and to each other, and for users to select from available stylistic sets.";
        
        private static Dictionary<string, FeatureInfo> features;
        
        static FeatureInfos()
        {
            features = new Dictionary<string, FeatureInfo>();
            features["aalt"] = FeatureInfo.Create("aalt", "Access All Alternates", FeatureRegistration.Adobe, "This feature makes all variations of a selected character accessible. This serves several purposes: An application may not support the feature by which the desired glyph would normally be accessed; the user may need a glyph outside the context supported by the normal substitution, or the user may not know what feature produces the desired glyph. Since many-to-one substitutions are not covered, ligatures would not appear in this table unless they were variant forms of another ligature.");
            features["abvf"] = FeatureInfo.Create("abvf", "Above-base Forms", FeatureRegistration.Microsoft, "Substitutes the above-base form of a vowel. In particular, this feature is used for certain “split” vowels in Khmer or other Brahmi-derived scripts if the character has separate components that appear before and above a consonant, but the Unicode character for the vowel does not have a decomposition into separate characters for the two components.", overridesAllOtherFeatures: true);
            features["abvm"] = FeatureInfo.Create("abvm", "Above-base Mark Positioning", FeatureRegistration.Microsoft, "Positions marks above base glyphs.");
            features["abvs"] = FeatureInfo.Create("abvs", "Above-base Substitutions", FeatureRegistration.Microsoft, "Substitutes a ligature for a base glyph and mark that’s above it.");
            features["afrc"] = FeatureInfo.Create("afrc", "Alternative Fractions", FeatureRegistration.Microsoft, "Replaces figures separated by a slash with an alternative form.", overridesAllOtherFeatures: true);
            features["akhn"] = FeatureInfo.Create("akhn", "Akhand", FeatureRegistration.Microsoft, "Preferentially substitutes default glyphs for a sequence of characters with a ligature. This substitution is done irrespective of any characters that may precede or follow the sequence.", enableFeatures: new [] {"nukt", "akhn", "rphf", "rkrf", "pref", "blwf", "half", "pstf", "cjct"});
            features["blwf"] = FeatureInfo.Create("blwf", "Below-base Forms", FeatureRegistration.Microsoft, "Substitutes the below-base form of a consonant in conjuncts.", enableFeatures: new [] {"nukt", "akhn", "rphf", "rkrf", "pref", "blwf", "half", "pstf", "cjct"});
            features["blwm"] = FeatureInfo.Create("blwm", "Below-base Mark Positioning", FeatureRegistration.Microsoft, "Positions marks below base glyphs.");
            features["blws"] = FeatureInfo.Create("blws", "Below-base Substitutions", FeatureRegistration.Microsoft, "Produces ligatures that comprise of base glyph and below-base forms.", overridesAllOtherFeatures: true);
            features["calt"] = FeatureInfo.Create("calt", "Contextual Alternates", FeatureRegistration.Adobe, "In specified situations, replaces default glyphs with alternate forms which provide better joining behavior. Used in script typefaces which are designed to have some or all of their glyphs join.");
            features["case"] = FeatureInfo.Create("case", "Case-Sensitive Forms", FeatureRegistration.Adobe, "Shifts various punctuation marks up to a position that works better with all-capital sequences or sets of lining figures; also changes oldstyle figures to lining figures. By default, glyphs in a text face are designed to work with lowercase characters. Some characters should be shifted vertically to fit the higher visual center of all-capital or lining text. Also, lining figures are the same height (or close to it) as capitals, and fit much better with all-capital text.");
            features["ccmp"] = FeatureInfo.Create("ccmp", "Glyph Composition/Decomposition", FeatureRegistration.Microsoft, "To minimize the number of glyph alternates, it is sometimes desirable to decompose the default glyph for a character into two or more glyphs. Additionally, it may be preferable to compose default glyphs for two or more characters into a single glyph for better glyph processing. This feature permits such composition/decomposition. The feature should be processed as the first feature processed, and should be processed only when it is called.", FeatureState.On);
            features["cfar"] = FeatureInfo.Create("cfar", "Conjunct Form After Ro", FeatureRegistration.Microsoft, "Substitutes alternate below-base or post-base forms in Khmer script when occurring after conjoined Ro (“Coeng Ra”).");
            features["chws"] = FeatureInfo.Create("chws", "Contextual Half-width Spacing", FeatureRegistration.AdobeW3C, "Contextually re-spaces glyphs designed to be set on full-em widths, fitting them onto individual half-em horizontal widths, to approximate more sophisticated text layout, such as what is described in Requirements for Japanese Text Layout (JLREQ) or similar CJK text-layout specifications that expect half-width forms of characters whose default glyphs are full-width.* This feature differs from 'halt' in that the re-spacing is contextual. This feature may be invoked to get better fit for punctuation or symbol glyphs without disrupting the monospaced alignment, such as for UIs or terminal apps.", disableFeatures: new []{"fwid", "halt", "hwid", "palt", "pwid", "qwid", "twid", "kern"});
            features["cjct"] = FeatureInfo.Create("cjct", "Conjunct Forms", FeatureRegistration.Microsoft, "Produces conjunct forms of consonants in Indic scripts. This is similar to the Akhands feature, but is applied at a different sequential point in the process of shaping an Indic syllable.", enableFeatures: new []{"nukt", "akhn", "rphf", "rkrf", "pref", "blwf", "half", "pstf", "cjct"});
            features["clig"] = FeatureInfo.Create("clig", "Contextual Ligatures", FeatureRegistration.Adobe, "Replaces a sequence of glyphs with a single glyph which is preferred for typographic purposes. Unlike other ligature features, 'clig' specifies the context in which the ligature is recommended. This capability is important in some script designs and for swash ligatures.", FeatureState.On);
            features["cpct"] = FeatureInfo.Create("cpct", "Centered CJK Punctuation", FeatureRegistration.Adobe, "Centers specific punctuation marks for those fonts that do not include centered and non-centered forms.", disableFeatures: new []{"tnum", "fwid", "hwid", "halt", "palt", "twid"});
            features["cpsp"] = FeatureInfo.Create("cpsp", "Capital Spacing", FeatureRegistration.Adobe, "Globally adjusts inter-glyph spacing for all-capital text. Most typefaces contain capitals and lowercase characters, and the capitals are positioned to work with the lowercase. When capitals are used for words, they need more space between them for legibility and esthetics. This feature would not apply to monospaced designs. Of course the user may want to override this behavior in order to do more pronounced letterspacing for esthetic reasons.");
            features["cswh"] = FeatureInfo.Create("cswh", "Contextual Swash", FeatureRegistration.Adobe, "This feature replaces default character glyphs with corresponding swash glyphs in a specified context. Note that there may be more than one swash alternate for a given character.");
            features["curs"] = FeatureInfo.Create("curs", "Cursive Positioning", FeatureRegistration.Microsoft, "This feature is used to position adjacent glyphs for cursive connections.");
            
            features["cv01"] = FeatureInfo.Create("cv01", "Character Variant 1", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv02"] = FeatureInfo.Create("cv02", "Character Variant 2", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv03"] = FeatureInfo.Create("cv03", "Character Variant 3", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv04"] = FeatureInfo.Create("cv04", "Character Variant 4", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv05"] = FeatureInfo.Create("cv05", "Character Variant 5", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv06"] = FeatureInfo.Create("cv06", "Character Variant 6", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv07"] = FeatureInfo.Create("cv07", "Character Variant 7", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv08"] = FeatureInfo.Create("cv08", "Character Variant 8", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv09"] = FeatureInfo.Create("cv09", "Character Variant 9", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv10"] = FeatureInfo.Create("cv10", "Character Variant 10", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv11"] = FeatureInfo.Create("cv11", "Character Variant 11", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv12"] = FeatureInfo.Create("cv12", "Character Variant 12", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv13"] = FeatureInfo.Create("cv13", "Character Variant 13", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv14"] = FeatureInfo.Create("cv14", "Character Variant 14", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv15"] = FeatureInfo.Create("cv15", "Character Variant 15", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv16"] = FeatureInfo.Create("cv16", "Character Variant 16", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv17"] = FeatureInfo.Create("cv17", "Character Variant 17", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv18"] = FeatureInfo.Create("cv18", "Character Variant 18", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv19"] = FeatureInfo.Create("cv19", "Character Variant 19", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv20"] = FeatureInfo.Create("cv20", "Character Variant 20", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv21"] = FeatureInfo.Create("cv21", "Character Variant 21", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv22"] = FeatureInfo.Create("cv22", "Character Variant 22", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv23"] = FeatureInfo.Create("cv23", "Character Variant 23", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv24"] = FeatureInfo.Create("cv24", "Character Variant 24", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv25"] = FeatureInfo.Create("cv25", "Character Variant 25", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv26"] = FeatureInfo.Create("cv26", "Character Variant 26", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv27"] = FeatureInfo.Create("cv27", "Character Variant 27", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv28"] = FeatureInfo.Create("cv28", "Character Variant 28", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv29"] = FeatureInfo.Create("cv29", "Character Variant 29", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv30"] = FeatureInfo.Create("cv30", "Character Variant 30", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv31"] = FeatureInfo.Create("cv31", "Character Variant 31", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv32"] = FeatureInfo.Create("cv32", "Character Variant 32", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv33"] = FeatureInfo.Create("cv33", "Character Variant 33", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv34"] = FeatureInfo.Create("cv34", "Character Variant 34", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv35"] = FeatureInfo.Create("cv35", "Character Variant 35", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv36"] = FeatureInfo.Create("cv36", "Character Variant 36", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv37"] = FeatureInfo.Create("cv37", "Character Variant 37", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv38"] = FeatureInfo.Create("cv38", "Character Variant 38", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv39"] = FeatureInfo.Create("cv39", "Character Variant 39", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv40"] = FeatureInfo.Create("cv40", "Character Variant 40", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv41"] = FeatureInfo.Create("cv41", "Character Variant 41", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv42"] = FeatureInfo.Create("cv42", "Character Variant 42", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv43"] = FeatureInfo.Create("cv43", "Character Variant 43", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv44"] = FeatureInfo.Create("cv44", "Character Variant 44", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv45"] = FeatureInfo.Create("cv45", "Character Variant 45", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv46"] = FeatureInfo.Create("cv46", "Character Variant 46", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv47"] = FeatureInfo.Create("cv47", "Character Variant 47", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv48"] = FeatureInfo.Create("cv48", "Character Variant 48", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv49"] = FeatureInfo.Create("cv49", "Character Variant 49", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv50"] = FeatureInfo.Create("cv50", "Character Variant 50", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv51"] = FeatureInfo.Create("cv51", "Character Variant 51", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv52"] = FeatureInfo.Create("cv52", "Character Variant 52", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv53"] = FeatureInfo.Create("cv53", "Character Variant 53", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv54"] = FeatureInfo.Create("cv54", "Character Variant 54", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv55"] = FeatureInfo.Create("cv55", "Character Variant 55", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv56"] = FeatureInfo.Create("cv56", "Character Variant 56", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv57"] = FeatureInfo.Create("cv57", "Character Variant 57", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv58"] = FeatureInfo.Create("cv58", "Character Variant 58", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv59"] = FeatureInfo.Create("cv59", "Character Variant 59", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv60"] = FeatureInfo.Create("cv60", "Character Variant 60", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv61"] = FeatureInfo.Create("cv61", "Character Variant 61", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv62"] = FeatureInfo.Create("cv62", "Character Variant 62", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv63"] = FeatureInfo.Create("cv63", "Character Variant 63", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv64"] = FeatureInfo.Create("cv64", "Character Variant 64", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv65"] = FeatureInfo.Create("cv65", "Character Variant 65", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv66"] = FeatureInfo.Create("cv66", "Character Variant 66", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv67"] = FeatureInfo.Create("cv67", "Character Variant 67", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv68"] = FeatureInfo.Create("cv68", "Character Variant 68", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv69"] = FeatureInfo.Create("cv69", "Character Variant 69", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv70"] = FeatureInfo.Create("cv70", "Character Variant 70", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv71"] = FeatureInfo.Create("cv71", "Character Variant 71", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv72"] = FeatureInfo.Create("cv72", "Character Variant 72", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv73"] = FeatureInfo.Create("cv73", "Character Variant 73", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv74"] = FeatureInfo.Create("cv74", "Character Variant 74", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv75"] = FeatureInfo.Create("cv75", "Character Variant 75", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv76"] = FeatureInfo.Create("cv76", "Character Variant 76", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv77"] = FeatureInfo.Create("cv77", "Character Variant 77", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv78"] = FeatureInfo.Create("cv78", "Character Variant 78", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv79"] = FeatureInfo.Create("cv79", "Character Variant 79", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv80"] = FeatureInfo.Create("cv80", "Character Variant 80", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv81"] = FeatureInfo.Create("cv81", "Character Variant 81", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv82"] = FeatureInfo.Create("cv82", "Character Variant 82", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv83"] = FeatureInfo.Create("cv83", "Character Variant 83", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv84"] = FeatureInfo.Create("cv84", "Character Variant 84", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv85"] = FeatureInfo.Create("cv85", "Character Variant 85", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv86"] = FeatureInfo.Create("cv86", "Character Variant 86", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv87"] = FeatureInfo.Create("cv87", "Character Variant 87", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv88"] = FeatureInfo.Create("cv88", "Character Variant 88", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv89"] = FeatureInfo.Create("cv89", "Character Variant 89", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv90"] = FeatureInfo.Create("cv90", "Character Variant 90", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv91"] = FeatureInfo.Create("cv91", "Character Variant 91", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv92"] = FeatureInfo.Create("cv92", "Character Variant 92", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv93"] = FeatureInfo.Create("cv93", "Character Variant 93", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv94"] = FeatureInfo.Create("cv94", "Character Variant 94", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv95"] = FeatureInfo.Create("cv95", "Character Variant 95", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv96"] = FeatureInfo.Create("cv96", "Character Variant 96", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv97"] = FeatureInfo.Create("cv97", "Character Variant 97", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv98"] = FeatureInfo.Create("cv98", "Character Variant 98", FeatureRegistration.Microsoft, cvFeatureDescription);
            features["cv99"] = FeatureInfo.Create("cv99", "Character Variant 99", FeatureRegistration.Microsoft, cvFeatureDescription);
            
            features["c2pc"] = FeatureInfo.Create("c2pc", "Petite Capitals From Capitals", FeatureRegistration.TiroTypeworksEmigre, "This feature turns capital characters into petite capitals. It is generally used for words which would otherwise be set in all caps, such as acronyms, but which are desired in petite-cap form to avoid disrupting the flow of text. See the 'pcap' feature description for notes on the relationship of caps, smallcaps and petite caps.");
            features["c2sc"] = FeatureInfo.Create("c2sc", "Small Capitals From Capitals", FeatureRegistration.Adobe, "This feature turns capital characters into small capitals. It is generally used for words which would otherwise be set in all caps, such as acronyms, but which are desired in small-cap form to avoid disrupting the flow of text.");
            features["dist"] = FeatureInfo.Create("dist", "Distances", FeatureRegistration.Microsoft, "Provides a means to control distance between glyphs.");
            features["dlig"] = FeatureInfo.Create("dlig", "Discretionary Ligatures", FeatureRegistration.Adobe, "Replaces a sequence of glyphs with a single glyph which is preferred for typographic purposes. This feature covers those ligatures which may be used for special effect, at the user’s preference.");
            features["dnom"] = FeatureInfo.Create("dnom", "Denominators", FeatureRegistration.Adobe, "Replaces selected figures which follow a slash with denominator figures.");
            features["dtls"] = FeatureInfo.Create("dtls", "Dotless Forms", FeatureRegistration.Microsoft, "This feature provides dotless forms for Math Alphanumeric characters, such as U+1D422 MATHEMATICAL BOLD SMALL I, U+1D423 MATHEMATICAL BOLD SMALL J, U+1D456 U+MATHEMATICAL ITALIC SMALL I, U+1D457 MATHEMATICAL ITALIC SMALL J, and so on. The dotless forms are to be used as base forms for placing mathematical accents over them.");
            features["expt"] = FeatureInfo.Create("expt", "Expert Forms", FeatureRegistration.Adobe, "Like the JIS78 Forms feature, this feature replaces standard forms in Japanese fonts with corresponding forms preferred by typographers. Although most of the JIS78 substitutions are included, the expert substitution goes on to handle many more characters.", allowedFeatures: new []{"palt", "vpal", "vert", "vrt2"});
            
            features["falt"] = FeatureInfo.Create("falt", "Final Glyph on Line Alternates", FeatureRegistration.Microsoft, "Replaces line final glyphs with alternate forms specifically designed for this purpose (they would have less or more advance width as need may be), to help justification of text.");
            features["fin2"] = FeatureInfo.Create("fin2", "Terminal Form #2", FeatureRegistration.Microsoft, "Used to replace the Alaph glyph at the end of Syriac words with its appropriate form, when the preceding base character cannot be joined to, and that preceding base character is not a Dalath, Rish, or dotless Dalath-Rish.");
            features["fin3"] = FeatureInfo.Create("fin3", "Terminal Form #3", FeatureRegistration.Microsoft, "Used to Alaph glyphs at the end of Syriac words when the preceding base character is a Dalath, Rish, or dotless Dalath-Rish.");
            features["fina"] = FeatureInfo.Create("fina", "Terminal Forms", FeatureRegistration.MicrosoftAdobe, "Replaces glyphs for characters that have applicable joining properties with an alternate form when occurring in a final context");
            features["flac"] = FeatureInfo.Create("flac", "Flattened ascent forms", FeatureRegistration.Microsoft, "This feature provides flattened forms of accents to be used over high-rise bases such as capitals. This feature should only change the shape of the accent and should not move it in the vertical or horizontal direction. Moving of the accents is done by the math layout engine. Accents are flattened by the Math engine if their base is higher than MATH.MathConstants. FlattenedAccentBaseHeight.");
            features["frac"] = FeatureInfo.Create("frac", "Fractions", FeatureRegistration.MicrosoftAdobe, "Replaces figures (digits) separated by a slash (U+002F) with “common” (diagonal) fractions.");
            features["fwid"] = FeatureInfo.Create("fwid", "Full Widths", FeatureRegistration.Adobe, "Replaces glyphs set on other widths with glyphs set on full (usually em) widths. In a CJKV font, this may include “lower ASCII” Latin characters and various symbols. In a European font, this feature replaces proportionally-spaced glyphs with monospaced glyphs, which are generally set on widths of 0.6 em.", disableFeatures: new []{"tnum", "halt", "hwid", "palt", "pwid", "qwid", "twid", "kern"});
            features["half"] = FeatureInfo.Create("half", "Half Forms", FeatureRegistration.Microsoft, "Produces the half forms of consonants in Indic scripts.");
            features["haln"] = FeatureInfo.Create("haln", "Halant Forms", FeatureRegistration.Microsoft, "Produces the halant forms of consonants in Indic scripts (that is, precomposed glyphs for consonant with the halant).", overridesAllOtherFeatures: true);
            features["halt"] = FeatureInfo.Create("halt", "Alternate Half Widths", FeatureRegistration.Adobe, "Re-spaces glyphs designed to be set on full-em widths, fitting them onto half-em widths, to approximate more sophisticated text layout, such as what is described in Requirements for Japanese Text Layout (JLREQ) or similar CJKV text-layout specifications that expect half-width forms of characters whose default glyphs are full-width.* This feature differs from 'hwid' in that it is not used to substitute new glyphs.", disableFeatures: new []{"fwid", "hwid", "palt", "tnum", "twid", "kern"});
            features["hist"] = FeatureInfo.Create("hist", "Historical Forms", FeatureRegistration.MicrosoftAdobe, "Some letterforms were in common use in the past, but appear anachronistic today. The best-known example is the long form of s; others would include the old Fraktur k. Some fonts include the historical forms as alternates, so they can be used for a “period” effect. This feature replaces the default (current) forms with the historical alternates. While some ligatures are also used for historical effect, this feature deals only with single characters.");
            features["hkna"] = FeatureInfo.Create("hkna", "Horizontal Kana Alternates", FeatureRegistration.Adobe, "Replaces standard kana with forms that have been specially designed for only horizontal writing. This is a typographic optimization for improved fit and more even color. Also see 'vkna'.");
            features["hlig"] = FeatureInfo.Create("hlig", "Historical Ligatures", FeatureRegistration.Microsoft, "Some ligatures were in common use in the past, but appear anachronistic today. Some fonts include the historical forms as alternates, so they can be used for a “period” effect. This feature replaces the default (current) forms with the historical alternates.", overridesAllOtherFeatures: true);
            features["hojo"] = FeatureInfo.Create("hojo", "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)", FeatureRegistration.Adobe, "The JIS X 0212-1990 (aka, “Hojo Kanji”) and JIS X 0213:2004 character sets overlap significantly. In some cases their prototypical glyphs differ. When building fonts that support both JIS X 0212-1990 and JIS X 0213:2004 (such as those supporting the Adobe-Japan 1-6 character collection), it is recommended that JIS X 0213:2004 forms be preferred as the encoded form. The 'hojo' feature is used to access the JIS X 0212-1990 glyphs for the cases when the JIS X 0213:2004 form is encoded.");
            features["hwid"] = FeatureInfo.Create("hwid", "Half Widths", FeatureRegistration.Adobe, "Replaces glyphs on proportional widths, or fixed widths other than half an em, with glyphs on half-em (en) widths. Many CJKV fonts have glyphs which are set on multiple widths; this feature selects the half-em version. There are various contexts in which this is the preferred behavior, including compatibility with older desktop documents.", disableFeatures: new []{ "tnum", "fwid", "halt", "qwid", "twid", "kern"});
            features["init"] = FeatureInfo.Create("init", "Initial Forms", FeatureRegistration.MicrosoftAdobe, "Replaces glyphs for characters that have applicable joining properties with an alternate form when occurring in an initial context.");
            features["isol"] = FeatureInfo.Create("isol", "Isolated Forms", FeatureRegistration.Microsoft, "Replaces glyphs for characters that have applicable joining properties with an alternate form when occurring in a isolate (non-joining) context.");
            features["ital"] = FeatureInfo.Create("ital", "Italics", FeatureRegistration.Adobe, "Some fonts (such as Adobe’s Pro Japanese fonts) will have both Roman and Italic forms of some characters in a single font. This feature replaces the Roman glyphs with the corresponding Italic glyphs.");
            features["jalt"] = FeatureInfo.Create("jalt", "Justification Alternates", FeatureRegistration.Microsoft, "Improves justification of text by replacing glyphs with alternate forms specifically designed for this purpose (they would have less or more advance width as need may be).");
            features["jp78"] = FeatureInfo.Create("jp78", "JIS78 Forms", FeatureRegistration.Adobe, "This feature replaces default (JIS90) Japanese glyphs with the corresponding forms from the JIS C 6226-1978 (JIS78) specification.", overridesAllOtherFeatures: true, allowedFeatures: new []{"palt", "vpal", "vert", "vrt2"});
            features["jp83"] = FeatureInfo.Create("jp83", "JIS83 Forms", FeatureRegistration.Adobe, "This feature replaces default (JIS90) Japanese glyphs with the corresponding forms from the JIS X 0208-1983 (JIS83) specification.", overridesAllOtherFeatures: true, allowedFeatures: new []{"palt", "vpal", "vert", "vrt2"});
            features["jp90"] = FeatureInfo.Create("jp90", "JIS90 Forms", FeatureRegistration.Adobe, "This feature replaces Japanese glyphs from the JIS78 or JIS83 specifications with the corresponding forms from the JIS X 0208-1990 (JIS90) specification.", overridesAllOtherFeatures: true, allowedFeatures: new []{"palt", "vpal", "vert", "vrt2"});
            features["jp04"] = FeatureInfo.Create("jp04", "JIS2004 Forms", FeatureRegistration.Adobe, "The National Language Council (NLC) of Japan has defined new glyph shapes for a number of JIS characters, which were incorporated into JIS X 0213:2004 as new prototypical forms. The 'jp04' feature is a subset of the 'nlck' feature, and is used to access these prototypical glyphs in a manner that maintains the integrity of JIS X 0213:2004.", overridesAllOtherFeatures: true, allowedFeatures: new []{"palt", "vpal", "vert", "vrt2"});
            
            features["kern"] = FeatureInfo.Create("kern", "Kerning", FeatureRegistration.MicrosoftAdobe, "Adjusts amount of space between glyphs, generally to provide optically consistent spacing between glyphs. Although a well-designed typeface has consistent inter-glyph spacing overall, some glyph combinations require adjustment for improved legibility. Besides standard adjustment in the horizontal direction, this feature can supply size-dependent kerning data via device tables, “cross-stream” kerning in the Y text direction, and adjustment of glyph placement independent of the advance adjustment. Note that this feature may apply to runs of more than two glyphs, and would not be used in monospaced fonts. Also note that this feature does not apply to text set vertically.", enableFeatures: new []{"palt"});
            features["lfbd"] = FeatureInfo.Create("lfbd", "Left Bounds", FeatureRegistration.Adobe, "Aligns glyphs by their apparent left extents at the left ends of horizontal lines of text, replacing the default behavior of aligning glyphs by their origins. This feature is called by the Optical Bounds ('opbd') feature.");
            features["liga"] = FeatureInfo.Create("liga", "Standard Ligatures", FeatureRegistration.MicrosoftAdobe, "Replaces a sequence of glyphs with a single glyph which is preferred for typographic purposes. This feature covers the ligatures which the designer/manufacturer judges should be used in normal conditions.");
            features["ljmo"] = FeatureInfo.Create("ljmo", "Leading Jamo Forms", FeatureRegistration.Microsoft, "Substitutes the leading jamo form of a cluster.", overridesAllOtherFeatures: true);
            features["lnum"] = FeatureInfo.Create("lnum", "Lining Figures", FeatureRegistration.Adobe, "This feature changes selected non-lining figures (digits) to lining figures.");
            features["locl"] = FeatureInfo.Create("locl", "Localized Forms", FeatureRegistration.TiroTypeworksEmigre, "Many scripts used to write multiple languages over wide geographical areas have developed localized variant forms of specific letters, which are used by individual literary communities. For example, a number of letters in the Bulgarian and Serbian alphabets have forms distinct from their Russian counterparts and from each other. In some cases the localized form differs only subtly from the script “norm”, in others the forms are radically distinct. This feature enables localized forms of glyphs to be substituted for default forms.");
            features["ltra"] = FeatureInfo.Create("ltra", "Left-to-right glyph alternates", FeatureRegistration.Adobe, "This feature applies glyphic variants (other than mirrored forms) appropriate for left-to-right text (for mirrored forms, see 'ltrm').", enableFeatures: new [] {"ccmp", "locl"});
            features["ltrm"] = FeatureInfo.Create("ltrm", "Left-to-right mirrored forms", FeatureRegistration.Adobe, "This feature applies mirrored forms appropriate for left-to-right text. (For left-to-right glyph alternates, see 'ltra').", enableFeatures: new [] {"ccmp", "locl"});
            features["mark"] = FeatureInfo.Create("mark", "Mark Positioning", FeatureRegistration.Microsoft, "Positions mark glyphs with respect to base glyphs.");
            features["med2"] = FeatureInfo.Create("med2", "Medial Forms #2", FeatureRegistration.Microsoft, "Used to replace Alaph glyphs in the middle of Syriac words when the preceding base character can be joined to. This feature is used only for the Syriac script Alaph character.");
            features["medi"] = FeatureInfo.Create("medi", "Medial Forms", FeatureRegistration.MicrosoftAdobe, "Replaces glyphs for characters that have applicable joining properties with an alternate form when occurring in a medial context. This applies to characters that have the Unicode Joining_Type property value Dual_Joining.");
            features["mgrk"] = FeatureInfo.Create("mgrk", "Mathematical Greek", FeatureRegistration.Adobe, "Replaces standard typographic forms of Greek glyphs with corresponding forms commonly used in mathematical notation (which are a subset of the Greek alphabet).");
            features["mkmk"] = FeatureInfo.Create("mkmk", "Mark to Mark Positioning", FeatureRegistration.Microsoft, "Positions marks with respect to other marks. Required in various non-Latin scripts like Arabic.", FeatureState.On);
            features["nalt"] = FeatureInfo.Create("nalt", "Alternate Annotation Forms", FeatureRegistration.Adobe, "Replaces default glyphs with various notational forms (e.g. glyphs placed in open or solid circles, squares, parentheses, diamonds or rounded boxes). In some cases an annotation form may already be present, but the user may want a different one.", overridesAllOtherFeatures: true, allowedFeatures: new []{"vert", "vrt2"});
            features["nlck"] = FeatureInfo.Create("nlck", "NLC Kanji Forms", FeatureRegistration.Adobe, "The National Language Council (NLC) of Japan has defined new glyph shapes for a number of JIS characters in 2000. The 'nlck' feature is used to access those glyphs.");
            features["nukt"] = FeatureInfo.Create("nukt", "Nukta Forms", FeatureRegistration.Microsoft, "Produces Nukta forms in Indic scripts.");
            features["numr"] = FeatureInfo.Create("numr", "Numerators", FeatureRegistration.Adobe, "Replaces selected figures (digits) which precede a slash with numerator figures, and replaces the typographic slash with the fraction slash.");
            features["onum"] = FeatureInfo.Create("onum", "Oldstyle Figures", FeatureRegistration.MicrosoftAdobe, "This feature changes selected figures from the default or lining style to oldstyle form.");
            features["ordn"] = FeatureInfo.Create("ordn", "Ordinals", FeatureRegistration.Adobe, "Replaces default alphabetic glyphs with the corresponding ordinal forms for use after figures. One exception to the follows-a-figure rule is the numero character (U+2116), which is actually a ligature substitution, but is best accessed through this feature.");
            features["ornm"] = FeatureInfo.Create("ornm", "Ornaments", FeatureRegistration.Adobe, "This is a dual-function feature, which uses two input methods to give the user access to ornament glyphs (e.g. fleurons, dingbats and border elements) in the font. One method replaces the bullet character with a selection from the full set of available ornaments; the other replaces specific “lower ASCII” characters with ornaments assigned to them. The first approach supports the general or browsing user; the second supports the power user.", overridesAllOtherFeatures: true);
            
            features["palt"] = FeatureInfo.Create("palt", "Proportional Alternate Widths", FeatureRegistration.Adobe, "Re-spaces glyphs designed to be set on full-em widths, fitting them onto individual (more or less proportional) horizontal widths. This differs from 'pwid' in that it does not substitute new glyphs (GPOS, not GSUB feature). The user may prefer the monospaced form, or may simply want to ensure that the glyph is well-fit and not rotated in vertical setting (Latin forms designed for proportional spacing would be rotated).", disableFeatures: new []{"fwid", "halt", "hwid", "qwid", "twid"});
            features["pcap"] = FeatureInfo.Create("pcap", "Petite Capitals", FeatureRegistration.TiroTypeworksEmigre, "Some fonts contain an additional size of capital letters, shorter than the regular smallcaps and whimsically referred to as petite caps. Such forms are most likely to be found in designs with a small lowercase x-height, where they better harmonise with lowercase text than the taller smallcaps (for examples of petite caps, see the Emigre type families Mrs Eaves and Filosofia). This feature turns glyphs for lowercase characters into petite capitals. Forms related to petite capitals, such as specially designed figures, may be included.");
            features["pkna"] = FeatureInfo.Create("pkna", "Proportional Kana", FeatureRegistration.Adobe, "Replaces glyphs, kana and kana-related, set on uniform widths (half or full-width) with proportional glyphs.", disableFeatures: new []{"fwid", "halt", "hwid", "palt", "pwid", "qwid", "twid", "vhal"});
            features["pnum"] = FeatureInfo.Create("pnum", "Proportional Figures", FeatureRegistration.MicrosoftAdobe, "Replaces figure glyphs set on uniform (tabular) widths with corresponding glyphs set on glyph-specific (proportional) widths. Tabular widths will generally be the default, but this cannot be safely assumed. Of course this feature would not be present in monospaced designs.");
            features["pref"] = FeatureInfo.Create("pref", "Pre-base Forms", FeatureRegistration.Microsoft, "Substitutes the pre-base form of a consonant.");
            features["pres"] = FeatureInfo.Create("pres", "Pre-base Substitutions", FeatureRegistration.Microsoft, "Produces the pre-base forms of conjuncts in Indic scripts. It can also be used to substitute the appropriate glyph variant for pre-base vowel signs.", overridesAllOtherFeatures: true);
            features["pstf"] = FeatureInfo.Create("pstf", "Post-base Forms", FeatureRegistration.Microsoft, "Substitutes the post-base form of a consonant.");
            features["psts"] = FeatureInfo.Create("psts", "Post-base Substitutions", FeatureRegistration.Microsoft, "Substitutes a sequence of a base glyph and post-base glyph, with its ligaturised form.", overridesAllOtherFeatures: true);
            features["pwid"] = FeatureInfo.Create("pwid", "Proportional Widths", FeatureRegistration.Adobe, "Replaces glyphs set on uniform widths (typically full or half-em) with proportionally spaced glyphs. The proportional variants are often used for the Latin characters in CJKV fonts, but may also be used for Kana in Japanese fonts.", enableFeatures: new []{ "kern" }, disableFeatures: new []{"fwid", "halt", "hwid", "palt", "qwid", "twid", "valt", "vhal"} );
            features["qwid"] = FeatureInfo.Create("qwid", "Quarter Widths", FeatureRegistration.Adobe, "Replaces glyphs on other widths with glyphs set on widths of one quarter of an em (half an en). The characters involved are normally figures and some forms of punctuation.", disableFeatures: new []{"fwid", "halt", "hwid", "twid", "kern"});
            features["rand"] = FeatureInfo.Create("rand", "Randomize", FeatureRegistration.Adobe, "In order to emulate the irregularity and variety of handwritten text, this feature allows multiple alternate forms to be used.");
            features["rclt"] = FeatureInfo.Create("rclt", "Required Contextual Alternates", FeatureRegistration.Microsoft, "In specified situations, replaces default glyphs with alternate forms which provide for better joining behavior or other glyph relationships. Especially important in script typefaces which are designed to have some or all of their glyphs join, but applicable also to e.g. variants to improve spacing. This feature is similar to 'calt', but with the difference that it should not be possible to turn off 'rclt' substitutions: they are considered essential to correct layout of the font.");
            features["rkrf"] = FeatureInfo.Create("rkrf", "Rakar Forms", FeatureRegistration.Microsoft, "Produces conjoined forms for consonants with rakar in Devanagari and Gujarati scripts.");
            features["rlig"] = FeatureInfo.Create("rlig", "Required Ligatures", FeatureRegistration.Microsoft, "Replaces a sequence of glyphs with a single glyph which is preferred for typographic purposes. This feature covers those ligatures, which the script determines as required to be used in normal conditions. This feature is important for some scripts to insure correct glyph formation.");
            features["rphf"] = FeatureInfo.Create("rphf", "Reph Form", FeatureRegistration.Microsoft, "Substitutes the Reph form for a consonant and halant sequence.");
            features["rtbd"] = FeatureInfo.Create("rtbd", "Right Bounds", FeatureRegistration.Adobe, "Aligns glyphs by their apparent right extents at the right ends of horizontal lines of text, replacing the default behavior of aligning glyphs by their origins. This feature is called by the Optical Bounds ('opbd') feature.");
            features["rtla"] = FeatureInfo.Create("rtla", "Right-to-left alternates", FeatureRegistration.Adobe, "This feature applies glyphic variants (other than mirrored forms) appropriate for right-to-left text. (For mirrored forms, see 'rtlm'.)", enableFeatures: new []{"ccmp", "locl"});
            features["rtlm"] = FeatureInfo.Create("rtlm", "Right-to-left mirrored forms", FeatureRegistration.Adobe, "This feature applies mirrored forms appropriate for right-to-left text other than for those characters that would be covered by the character-level mirroring step performed by an OpenType layout engine. (For right-to-left glyph alternates, see 'rtla'.)");
            features["ruby"] = FeatureInfo.Create("ruby", "Ruby Notation Forms", FeatureRegistration.Adobe, "Japanese typesetting often uses smaller kana glyphs, generally in superscripted form, to clarify the meaning of kanji which may be unfamiliar to the reader. These are called “ruby”, from the old typesetting term for four-point-sized type. This feature identifies glyphs in the font which have been designed for this use, substituting them for the default designs.");
            features["rvrn"] = FeatureInfo.Create("rvrn", "Required Variation Alternates", FeatureRegistration.Microsoft, "This feature is used in fonts that support OpenType Font Variations in order to select alternate glyphs for particular variation instances. (For background on OpenType Font Variations, see OpenType Font Variations Overview.)");
            features["salt"] = FeatureInfo.Create("salt", "Stylistic Alternates", FeatureRegistration.Adobe, "Many fonts contain alternate glyph designs for a purely esthetic effect; these don’t always fit into a clear category like swash or historical. As in the case of swash glyphs, there may be more than one alternate form. This feature replaces the default forms with the stylistic alternates.");
            features["sinf"] = FeatureInfo.Create("sinf", "Scientific Inferiors", FeatureRegistration.MicrosoftAdobe, "Replaces lining or oldstyle figures (digits) with inferior figures (smaller glyphs which sit lower than the standard baseline, primarily for chemical or mathematical notation). May also replace glyphs for lowercase characters with alphabetic inferiors.");
            features["size"] = FeatureInfo.Create("size", "Optical size", FeatureRegistration.Adobe, "This feature stores two kinds of information about the optical size of the font: design size (the point size for which the font is optimized) and size range (the range of point sizes which the font can serve well), as well as other information which helps applications use the size range. The design size is useful for determining proper tracking behavior. The size range is useful in families which have fonts covering several ranges. Additional values serve to identify the set of fonts which share related size ranges, and to identify their shared name. Note that sizes refer to nominal final output size, and are independent of viewing magnification or resolution.", FeatureState.On);
            features["smcp"] = FeatureInfo.Create("smcp", "Small Capitals", FeatureRegistration.MicrosoftAdobe, "This feature turns glyphs for lowercase characters into small capitals. It is generally used for display lines set in Large & small caps, such as titles. Forms related to small capitals, such as oldstyle figures, may be included.");
            features["smpl"] = FeatureInfo.Create("smpl", "Simplified Forms", FeatureRegistration.Adobe, "Replaces “traditional” Chinese or Japanese forms with the corresponding “simplified” forms.", overridesAllOtherFeatures: true, allowedFeatures: new []{"palt", "vert", "vrt2"});
            
            features["ss01"] = FeatureInfo.Create("ss01", "Stylistic Set 1", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss02"] = FeatureInfo.Create("ss02", "Stylistic Set 2", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss03"] = FeatureInfo.Create("ss03", "Stylistic Set 3", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss04"] = FeatureInfo.Create("ss04", "Stylistic Set 4", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss05"] = FeatureInfo.Create("ss05", "Stylistic Set 5", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss06"] = FeatureInfo.Create("ss06", "Stylistic Set 6", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss07"] = FeatureInfo.Create("ss07", "Stylistic Set 7", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss08"] = FeatureInfo.Create("ss08", "Stylistic Set 8", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss09"] = FeatureInfo.Create("ss09", "Stylistic Set 9", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss10"] = FeatureInfo.Create("ss10", "Stylistic Set 10", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss11"] = FeatureInfo.Create("ss11", "Stylistic Set 11", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss12"] = FeatureInfo.Create("ss12", "Stylistic Set 12", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss13"] = FeatureInfo.Create("ss13", "Stylistic Set 13", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss14"] = FeatureInfo.Create("ss14", "Stylistic Set 14", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss15"] = FeatureInfo.Create("ss15", "Stylistic Set 15", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss16"] = FeatureInfo.Create("ss16", "Stylistic Set 16", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss17"] = FeatureInfo.Create("ss17", "Stylistic Set 17", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss18"] = FeatureInfo.Create("ss18", "Stylistic Set 18", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss19"] = FeatureInfo.Create("ss19", "Stylistic Set 19", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            features["ss20"] = FeatureInfo.Create("ss20", "Stylistic Set 20", FeatureRegistration.TiroTypeworks, ssFeatureDescription);
            
            features["ssty"] = FeatureInfo.Create("ssty", "Math script style alternates", FeatureRegistration.Microsoft, "This feature provides glyph variants adjusted to be more suitable for use in subscripts and superscripts. The script style forms should not be scaled or moved in the font; scaling and moving them is done by the math layout engine. Instead, the 'ssty' feature should provide glyph forms that result in shapes that look good as superscripts and subscripts when scaled and positioned by the Math engine. When designing the script forms, the font developer may assume that MATH.MathConstants.scriptPercentScaleDown and MATH.MathConstants.scriptScriptPercentScaleDown will be the scaling factors used by the Math engine.");
            features["stch"] = FeatureInfo.Create("stch", "Stretching Glyph Decomposition", FeatureRegistration.Microsoft, "Unicode characters, such as the Syriac Abbreviation Mark (U+070F), that enclose other characters need to be able to stretch in order to dynamically adapt to the width of the enclosed text. This feature defines a decomposition set consisting of an odd number of glyphs which describe the stretching glyph. The odd numbered glyphs in the decomposition are fixed reference points which are distributed evenly from the start to the end of the enclosed text. The even numbered glyphs may be repeated as necessary to fill the space between the fixed glyphs. The first and last glyphs may either be simple glyphs with width at the baseline, or mark glyphs. All other decomposition glyphs should have width, but must be defined as mark glyphs.");
            features["subs"] = FeatureInfo.Create("subs", "Subscript", FeatureRegistration.MicrosoftAdobe, "The 'subs' feature may replace a default glyph with a subscript glyph, or it may combine a glyph substitution with positioning adjustments for proper placement.");
            features["sups"] = FeatureInfo.Create("sups", "Superscript", FeatureRegistration.MicrosoftAdobe, "Replaces lining or oldstyle figures with superior figures (primarily for footnote indication), and replaces lowercase letters with superior letters (primarily for abbreviated French titles).");
            features["swsh"] = FeatureInfo.Create("swsh", "Swash", FeatureRegistration.MicrosoftAdobe, "This feature replaces default character glyphs with corresponding swash glyphs. Note that there may be more than one swash alternate for a given character.");
            features["titl"] = FeatureInfo.Create("titl", "Titling", FeatureRegistration.Adobe, "This feature replaces the default glyphs with corresponding forms designed specifically for titling. These may be all-capital and/or larger on the body, and adjusted for viewing at larger sizes.");
            features["tjmo"] = FeatureInfo.Create("tjmo", "Trailing Jamo Forms", FeatureRegistration.Microsoft, "Substitutes the trailing jamo form of a cluster.", overridesAllOtherFeatures: true);
            features["tnam"] = FeatureInfo.Create("tnam", "Traditional Name Forms", FeatureRegistration.Adobe, "Replaces “simplified” Japanese kanji forms with the corresponding “traditional” forms. This is equivalent to the Traditional Forms feature, but explicitly limited to the traditional forms considered proper for use in personal names (as many as 205 glyphs in some fonts).");
            features["tnum"] = FeatureInfo.Create("tnum", "Tabular Figures", FeatureRegistration.Adobe, "Replaces figure glyphs set on proportional widths with corresponding glyphs set on uniform (tabular) widths. Tabular widths will generally be the default, but this cannot be safely assumed. Of course this feature would not be present in monospaced designs.");
            features["trad"] = FeatureInfo.Create("trad", "Traditional Forms", FeatureRegistration.Adobe, "Replaces 'simplified' Chinese hanzi or Japanese kanji forms with the corresponding 'traditional' forms.");
            features["twid"] = FeatureInfo.Create("twid", "Third Widths", FeatureRegistration.Adobe, "Replaces glyphs on other widths with glyphs set on widths of one third of an em. The characters involved are normally figures and some forms of punctuation.", disableFeatures: new []{"fwid", "halt", "hwid", "qwid", "kern"});
            
            features["unic"] = FeatureInfo.Create("unic", "Unicase", FeatureRegistration.TiroTypeworks, "This feature maps upper- and lowercase letters to a mixed set of lowercase and small capital forms, resulting in a single case alphabet (for an example of unicase, see the Emigre type family Filosofia). The letters substituted may vary from font to font, as appropriate to the design. If aligning to the x-height, smallcap glyphs may be substituted, or specially designed unicase forms might be used. Substitutions might also include specially designed figures.");
            features["valt"] = FeatureInfo.Create("valt", "Alternate Vertical Metrics", FeatureRegistration.Adobe, "Repositions glyphs to visually center them within full-height metrics, for use in vertical setting. Applies to full-width Latin, Greek, or Cyrillic glyphs, which are typically included in East Asian fonts, and whose glyphs are aligned on a common horizontal baseline and not rotated relative to the page or text frame.", disableFeatures: new []{"vhal", "vpal", "kern"});
            features["vatu"] = FeatureInfo.Create("vatu", "Vattu Variants", FeatureRegistration.Microsoft, "In an Indic consonant conjunct, substitutes a ligature glyph for a base consonant and a following vattu (below-base) form of a conjoining consonant, or for a half form of a consonant and a following vattu form.");
            features["vchw"] = FeatureInfo.Create("vchw", "Vertical Contextual Half-width Spacing", FeatureRegistration.AdobeW3C, "Contextually re-spaces glyphs designed to be set on full-em heights, fitting them onto individual half-width vertical heights, to approximate more sophisticated text layout, such as what is described in Requirements for Japanese Text Layout (JLREQ) or similar CJK text-layout specifications that expect half-width forms of characters whose default glyphs are full-width.* This differs from 'vhal' in that the re-spacing is contextual. This feature may be invoked to get better fit for punctuation or symbol glyphs without disrupting the monospaced alignment.", disableFeatures: new []{"valt", "vhal", "vpal", "vkrn"});
            features["vert"] = FeatureInfo.Create("vert", "Vertical Alternates", FeatureRegistration.MicrosoftAdobe, "Transforms default glyphs into glyphs that are appropriate for upright presentation in vertical writing mode. While the glyphs for most characters in East Asian writing systems remain upright when set in vertical writing mode, some must be transformed — usually by rotation, shifting, or different component ordering — for vertical writing mode.");
            features["vhal"] = FeatureInfo.Create("vhal", "Alternate Vertical Half Metrics", FeatureRegistration.Adobe, "Re-spaces glyphs designed to be set on full-em heights, fitting them onto half-em heights. This differs from 'valt', which repositions a glyph but does not affect its advance.", disableFeatures: new []{ "valt", "vpal", "kern"});
            features["vjmo"] = FeatureInfo.Create("vjmo", "Vowel Jamo Forms", FeatureRegistration.Microsoft, "Substitutes the vowel jamo form of a cluster.", overridesAllOtherFeatures: true);
            features["vkna"] = FeatureInfo.Create("vkna", "Vertical Kana Alternates", FeatureRegistration.Adobe, "Replaces standard kana with forms that have been specially designed for only vertical writing. This is a typographic optimization for improved fit and more even color. Also see 'hkna'.");
            features["vkrn"] = FeatureInfo.Create("vkrn", "Vertical Kerning", FeatureRegistration.Adobe, "Adjusts amount of space between glyphs, generally to provide optically consistent spacing between glyphs. Although a well-designed typeface has consistent inter-glyph spacing overall, some glyph combinations require adjustment for improved legibility. Besides standard adjustment in the vertical direction, this feature can supply size-dependent kerning data via device tables, “cross-stream” kerning in the X text direction, and adjustment of glyph placement independent of the advance adjustment. Note that this feature may apply to runs of more than two glyphs, and would not be used in monospaced fonts. Also note that this feature applies only to text set vertically.", enableFeatures: new []{"vpal"});
            features["vpal"] = FeatureInfo.Create("vpal", "Proportional Alternate Vertical Metrics", FeatureRegistration.Adobe, "Re-spaces glyphs designed to be set on full-em heights, fitting them onto individual (more or less proportional) vertical heights. This differs from 'valt', which repositions a glyph but does not affect its advance.", disableFeatures: new []{"valt", "vhal"});
            features["vrt2"] = FeatureInfo.Create("vrt2", "Vertical Alternates and Rotation", FeatureRegistration.Adobe, "Replaces some fixed-width (half-, third- or quarter-width) or proportional-width glyphs (mostly Latin or katakana) with forms suitable for vertical writing (that is, rotated 90 degrees clockwise). Note that these are a superset of the glyphs covered in the 'vert' table.");
            features["vrtr"] = FeatureInfo.Create("vrtr", "Vertical Alternates for Rotation", FeatureRegistration.AdobeMicrosoftW3C, "Transforms default glyphs into glyphs that are appropriate for sideways presentation in vertical writing mode. While the glyphs for most characters in East Asian writing systems remain upright when set in vertical writing mode, glyphs for other characters — such as those of other scripts or for particular Western-style punctuation — are expected to be presented sideways in vertical writing.");
            features["zero"] = FeatureInfo.Create("zero", "Slashed Zero", FeatureRegistration.Adobe, "Some fonts contain both a default form of zero, and an alternative form which uses a diagonal slash through the counter. Especially in condensed designs, it can be difficult to distinguish between 0 and O (zero and capital O) in any situation where capitals and lining figures may be arbitrarily mixed. This feature allows the user to change from the default 0 to a slashed form.");
            
        }

        public static FeatureInfo GetFeature(string tag)
        {
            return features[tag];
        }
    }
}