<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Platforms>x64</Platforms>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>latest</LangVersion>
		<BaseOutputPath>..\..\output\Adamantium.Engine.Compiler\bin</BaseOutputPath>
	</PropertyGroup>
	<ItemGroup>
		<Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Adamantium.Graphics.Core\Adamantium.Graphics.Core.csproj" />
		<ProjectReference Include="..\Adamantium.Win32\Adamantium.Win32.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="obj\**" />
	</ItemGroup>

</Project>
