<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Platforms>x64</Platforms>
		<RootNamespace>Adamantium.UI.Playground</RootNamespace>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>latest</LangVersion>
		<BaseOutputPath>..\..\output\Adamantium.UI.Playground\bin</BaseOutputPath>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="Textures\texture.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Textures\texture.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<None Remove="ControlTemplateSchema.xsd" />
		<None Remove="Effects\structs.hlsl" />
		<None Remove="Effects\structs2.hlsl" />
		<None Remove="Effects\structs3.hlsl" />
		<None Remove="Effects\structs4.hlsl" />
		<None Remove="ResourceDictionarySchema.xsd" />
		<None Remove="Textures\texture2.jpg" />
		<Content Include="Textures\texture2.jpg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<None Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Adamantium.Graphics\Adamantium.Graphics.csproj" />
		<ProjectReference Include="..\Adamantium.Fonts\Adamantium.Fonts.csproj" />
		<ProjectReference Include="..\Adamantium.Game\Adamantium.Game.csproj" />
		<ProjectReference Include="..\Adamantium.UI\Adamantium.UI.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Adamantium.Core\Adamantium.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" SetTargetFramework="TargetFramework=netstandard2.0" />
		<ProjectReference Include="..\Adamantium.UI.Markup\Adamantium.UI.Markup.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
		<ProjectReference Include="..\Adamantium.UI.Generators\Adamantium.UI.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
		
		<ProjectReference Include="..\Adamantium.Engine.Generators\Adamantium.Engine.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
		<ProjectReference Include="..\Adamantium.EffectsCompiler\Adamantium.EffectsCompiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
		<ProjectReference Include="..\Adamantium.Mathematics\Adamantium.Mathematics.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" SetTargetFramework="TargetFramework=netstandard2.0" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="$(ProjectDir)**\*.xml" />
		<AdditionalFiles Include="$(ProjectDir)**\*.fx" />
		<AdditionalFiles Include="$(ProjectDir)**\*.hlsl" />
		<AdditionalFiles Include="ControlTemplateSchema.xsd" />
		<AdditionalFiles Include="ResourceDictionarySchema.xsd" />
		<CompilerVisibleProperty Include="RootNamespace" />
		<AdditionalFiles Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="obj\**" />
	</ItemGroup>

</Project>
