<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Platforms>x64</Platforms>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="atomicage-regular.ttf" />
      <None Remove="azoft-sans.ttf" />
      <None Remove="PlayfairDisplay-Regular.ttf" />
      <None Remove="Windsong.ttf" />
      <None Remove="OTFFonts\Poppins-Medium.otf" />
      <None Remove="OTFFonts\Glametrix-oj9A.otf" />
      <None Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adamantium.Mathematics\Adamantium.Mathematics.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BrotliSharpLib" Version="0.3.3" />
      <PackageReference Include="SharpZipLib" Version="1.4.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="obj\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="obj\**" />
    </ItemGroup>

</Project>
