using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Adamantium.Engine.Compiler.Converter.AutoGenerated;
using Adamantium.Engine.Compiler.Converter.Configs;
using Adamantium.Engine.Compiler.Converter.Containers;
using Adamantium.Engine.Compiler.Converter.Converters;
using Adamantium.Engine.Compiler.Converter.Parsers;
using Adamantium.Engine.Compiler.Models.ConversionUtils;
using Adamantium.Graphics.Core.Models;

namespace Adamantium.Engine.Compiler.Models.Converters
{
   public class ColladaConverter: ConverterBase
   {
      private ColladaConversionExecutor executor;

      public ColladaConverter(string filePath, ConversionConfig config) : base(filePath, config)
      {
         Parser = new ColladaFileParser(filePath);
      }

      /// <summary>Reading indices, triangulating and building the raw mesh never touch the scene tree, so they run
      /// in parallel. Attaching to the tree is sequential and in file order: otherwise the order of meshes in the
      /// model would depend on which thread got there first.</summary>
      private void ParseData(List<geometry> geometrys)
      {
         var prepared = new GeometryParts[geometrys.Count];
         var options = new ParallelOptions { CancellationToken = CancellationToken };
         Parallel.For(0, geometrys.Count, options, i => prepared[i] = PrepareGeometry(geometrys[i]));

         foreach (var parts in prepared)
         {
            AttachGeometry(parts);
         }
      }

      private void ParseData(List<image> images)
      {
         foreach (var image in images)
         {
            ParseData(image);
         }
      }

      private void ParseData(List<controller> controllers)
      {
         foreach (var controller in controllers)
         {
            ParseData(controller);
         }
      }

      private void ParseData(List<material> materials, List<effect> effects)
      {
         foreach (var material in materials)
         {
            ParseData(material, effects);
         }
      }

      private void ResolveMaterialsBinding(List<visual_scene> visualScenes)
      {
         //Resolve materials corresponding to geometry
         foreach (var visualScene in visualScenes)
         {
            executor.ResolveMaterialsBinding(SceneDataContainer, visualScene);
         }
      }

      private void ParseData(List<light> lights)
      {
         foreach (var light in lights)
         {
            ParseData(light);
         }
      }


      private void ParseData(List<camera> cameras)
      {
         foreach (var camera in cameras)
         {
            ParseData(camera);
         }
      }

      protected override void Convert()
      {
         ColladaDataContainer dataContainer = (ColladaDataContainer) Parser.ParseData(Config);
         if (!dataContainer.IsFileValid)
         {
            IsCancelled = true;
            return;
         }

         UnsupportedFeatures.AddRange(dataContainer.UnsupportedFeatures);

         executor = new ColladaConversionExecutor(Config, dataContainer.Axis);
         UpAxis = dataContainer.Axis;
         SceneDataContainer.Units = dataContainer.Units;

         try
         {
            ConvertLibraries(dataContainer);
         }
         finally
         {
            //Even when the parse threw, what it could not understand must be reported - especially then
            UnsupportedFeatures.AddRange(executor.UnsupportedFeatures);
         }
      }

      private void ConvertLibraries(ColladaDataContainer dataContainer)
      {
         CancellationToken.ThrowIfCancellationRequested();

         var controllerTask = Task.Run(() => ParseData(dataContainer.Controllers));

         ParseData(dataContainer.Images);
         ParseData(dataContainer.Cameras);
         ParseData(dataContainer.Lights);

         SceneDataContainer.Models = SceneDataContainer.CreateMesh(null, "", dataContainer.FileName);

         //Read the mesh tree so the import keeps the file's own hierarchy
         foreach (var visualScene in dataContainer.VisualScenes)
         {
            executor.GetMeshStructure(SceneDataContainer, visualScene, dataContainer.Geometries, dataContainer.Controllers);
         }
         //Geometry takes bone weights from the controller table, so wait for it here
         controllerTask.Wait();
         CancellationToken.ThrowIfCancellationRequested();

         var materialsTask = Task.Run(() => ParseData(dataContainer.Materials, dataContainer.Effects));
         //Animations read the controllers' bone lists (already built) and the visual-scene nodes, not the geometry
         var animationTask = Task.Run(() => ParseData(dataContainer.Animations, dataContainer.VisualScenes));

         ParseData(dataContainer.Geometries);
         // Strictly after geometry: the binding looks for meshes that already exist. There used to be a ContinueWith
         // here, which ran even when geometry threw and carried that exception away - the model arrived empty, silently.
         ResolveMaterialsBinding(dataContainer.VisualScenes);

         Task.WaitAll(materialsTask, animationTask);
      }

      #region Geometry

      private sealed record GeometryParts(List<IndicesContainer> Indices, Mesh Mesh, String MeshId, String MeshName);

      //Reads one mesh. Nothing in here touches the scene tree, so it runs alongside the neighbouring geometries
      private GeometryParts PrepareGeometry(geometry geometry)
      {
         List<RawIndicesSemanticData> rawIndicesList = executor.GetRawIndicesCollada(geometry);
         if (rawIndicesList == null)
         {
            return null;
         }

         List<IndicesContainer> indicesContainers = new List<IndicesContainer>();
         foreach (var indices in rawIndicesList)
         {
            indicesContainers.Add(executor.DistributeIndices(indices));
         }

         //Take the richest semantic of them all
         Dictionary<String, VertexSemantic> semanticIdMapping = new Dictionary<string, VertexSemantic>();
         foreach (var indices in rawIndicesList)
         {
            foreach (var mapping in indices.SemanticIdMapping)
            {
               if (!semanticIdMapping.ContainsKey(mapping.Key))
               {
                  semanticIdMapping.Add(mapping.Key, mapping.Value);
               }
            }
         }

         var mesh = executor.GetRawMesh(geometry, semanticIdMapping, out var meshId, out var meshName);
         return new GeometryParts(indicesContainers, mesh, meshId, meshName);
      }

      //Hangs the parsed geometry on the scene tree. Sequentially, always
      private void AttachGeometry(GeometryParts parts)
      {
         if (parts == null)
         {
            return;
         }

         if (SceneDataContainer.Controllers.TryGetValue(parts.MeshId, out var controller))
         {
            parts.Mesh.SetJointIndices(controller.BoneIndices);
            parts.Mesh.SetJointWeights(controller.BoneWeights);
         }

         executor.ConstructMesh(SceneDataContainer, parts.Indices, parts.Mesh, parts.MeshId, parts.MeshName);
      }

      #endregion


      #region Animation and controllers

      private void ParseData(controller controller)
      {
         SceneData.Controller comp = executor.GetControllerData(controller, FilePath);
         lock (SceneDataContainer.Controllers)
         {
            SceneDataContainer.Controllers.Add(comp.MeshId, comp);
         }
      }

      /// <summary>Animations are collected across the WHOLE library at once: one joint's channels legally sit in
      /// separate &lt;animation&gt; elements (that is how Blender exports), and parsing them one by one leaves the
      /// joint with nothing but its last channel.</summary>
      private void ParseData(List<animation> animations, List<visual_scene> visualScenes)
      {
         var nodes = ColladaConversionExecutor.IndexNodes(visualScenes);
         foreach (var frames in executor.GetAnimations(animations, nodes))
         {
            frames.ControllerId = ControllerFor(frames.JointId);
            SceneDataContainer.Animation[frames.FullName] = frames;
         }
      }

      //Whose joint this is. The controller's bone list is the authority; a substring of the name is the fallback
      private String ControllerFor(String jointId)
      {
         foreach (var controller in SceneDataContainer.Controllers)
         {
            if (controller.Value.JointNames.Contains(jointId))
            {
               return controller.Value.Name;
            }
         }

         foreach (var controller in SceneDataContainer.Controllers)
         {
            var name = controller.Value.Name;
            if (!String.IsNullOrEmpty(name) && jointId.Contains(name))
            {
               return name;
            }
         }
         return String.Empty;
      }

      #endregion


      #region Materials

      private void ParseData(material material, List<effect> effects)
      {
         instance_effect effectLink = material.instance_effect;
         String id = effectLink.url.Substring(1);
         foreach (effect effect in effects)
         {
            if (effect.id == id)
            {
               var materialComponent = executor.GetMaterial(effect);
               //Point at the material, not the effect, so the link between the geometry's material and the one in
               //the material library survives
               materialComponent.ID = material.id;
               lock (SceneDataContainer.Materials)
               {
                  SceneDataContainer.Materials.Add(materialComponent.ID, materialComponent);
                  break;
               }
            }
         }
      }

      #endregion


      #region Lights

      private void ParseData(light light)
      {
         var l = executor.GetLight(light);
         lock (SceneDataContainer.LightData)
         {
            SceneDataContainer.LightData.Add(l.ID, l);
         }
      }

      #endregion


      #region Cameras

      private void ParseData(camera camera)
      {
         var cam = executor.GetCamera(camera);
         lock (SceneDataContainer.CameraData)
         {
            SceneDataContainer.CameraData.Add(cam.ID, cam);
         }
      }

      #endregion


      #region Textures

      private void ParseData(image img)
      {
         SceneData.Image images = executor.GetImage(FilePath, img);
         SceneDataContainer.Images.Add(images.ID, images);
      }

      #endregion
   }
}
