using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using Adamantium.Engine.Compiler.Converter.AutoGenerated;
using Adamantium.Engine.Compiler.Converter.Configs;
using Adamantium.Engine.Compiler.Converter.Containers;
using Adamantium.Engine.Compiler.Models.ConversionUtils;
using Adamantium.Graphics.Core;
using Adamantium.Graphics.Core.Models;
using static Adamantium.Graphics.Core.Models.SceneData;

namespace Adamantium.Engine.Compiler.Converter.Parsers
{
   public class ColladaFileParser: ModelFileParser
   {
      private COLLADA model;
      private ColladaDataContainer dataContainer;
      private assetContributor[] contributor;
      private asset _asset;
      private Modules modules;
      private ConversionConfig config;

      public ColladaFileParser(String filePath) : base(filePath)
      {
         dataContainer = new ColladaDataContainer(filePath) {ConverterToUse = ConverterVariant.Collada};
      }

      public override DataContainer ParseData(ConversionConfig config)
      {
         this.config = config;
         //Nothing to parse if the file did not load
         if (LoadFile(dataContainer.FilePath))
         {
            ParseFile();
            GetMetadata();
         }

         if (IsEmpty())
         {
            dataContainer.IsFileValid = false;
         }

         return dataContainer;
      }

      protected Boolean LoadFile(string filePath)
      {
         try
         {
            model = COLLADA.Load(filePath);
            _asset = model.asset;
            contributor = _asset?.contributor;
            dataContainer.IsFileValid = true;
         }
         // Not just InvalidOperationException: broken XML gives XmlException, a missing or locked file gives
         // IOException, and both used to escape unhandled.
         catch (Exception exception) when (exception is InvalidOperationException or XmlException or IOException
                                                       or UnauthorizedAccessException)
         {
            dataContainer.IsFileValid = false;
            return false;
         }
         return true;
      }

      // An empty library (Blender's <library_images/>) leaves the array null rather than empty. This used to be
      // handled by catching NullReferenceException around the WHOLE parse - which swallowed every other error along
      // with it and handed back an incomplete model without a word.
      private static void Collect<T>(T[] source, List<T> destination, ref Modules modules, Modules module)
      {
         if (source == null) return;

         destination.AddRange(source);
         modules |= module;
      }

      private void ParseFile()
      {
         foreach (var item in model.Items)
         {
            switch (item)
            {
               case library_geometries geometries when config.GeometryEnabled:
                  Collect(geometries.geometry, dataContainer.Geometries, ref modules, Modules.Geometry);
                  break;

               case library_cameras cameras when config.CamerasEnabled:
                  Collect(cameras.camera, dataContainer.Cameras, ref modules, Modules.Cameras);
                  break;

               case library_visual_scenes visualScenes:
                  Collect(visualScenes.visual_scene, dataContainer.VisualScenes, ref modules, Modules.VisualScenes);
                  break;

               case library_animations animations when config.AnimationEnabled:
                  Collect(animations.animation, dataContainer.Animations, ref modules, Modules.Animation);
                  break;

               case library_controllers controllers when config.ControllersEnabled:
                  Collect(controllers.controller, dataContainer.Controllers, ref modules, Modules.Controllers);
                  break;

               case library_lights lights when config.LightsEnabled:
                  Collect(lights.light, dataContainer.Lights, ref modules, Modules.Light);
                  break;

               case library_images images when config.ImagesEnabled:
                  Collect(images.image, dataContainer.Images, ref modules, Modules.Images);
                  break;

               case library_materials materials when config.MaterialsEnabled:
                  Collect(materials.material, dataContainer.Materials, ref modules, Modules.Materials);
                  break;

               case library_effects effects when config.MaterialsEnabled:
                  Collect(effects.effect, dataContainer.Effects, ref modules, Modules.Materials);
                  break;

               // Geometry moved into <library_nodes> and pulled in through <instance_node> is not supported - such
               // a file imported empty, and silently. Let it at least say so.
               case library_nodes:
                  dataContainer.UnsupportedFeatures.Add(
                     "library_nodes/instance_node: this library's contents will not reach the model");
                  break;
            }
         }
         dataContainer.SortedModules = modules.Sort<Modules>();
      }


      #region Metadata

      private void GetMetadata()
      {
         FileMetadata metadata = new FileMetadata();
         string version = null;
         if (model.version == VersionType.Item141)
         {
            version = "1.4.1";
         }
         else if (model.version == VersionType.Item140)
         {
            version = "1.4.0";
         }
         else
         {
            version = model.version.ToString();
         }
         metadata.Version = version;

         // <contributor> is optional, and this method is not inside a try - a file without one used to throw here.
         var author = contributor is { Length: > 0 } ? contributor[0] : null;
         metadata.AuthoringTool = author?.authoring_tool;
         metadata.Author = author?.author;

         if (_asset != null)
         {
            metadata.CreationDate = _asset.created.Date;
            metadata.ModificationDate = _asset.modified.Date;

            // The scale comes from meter, not name: the name is free-form ("centimeter", "cm", "units"), and when it
            // failed to parse the model silently arrived at the wrong scale. The name is kept only as a label.
            if (_asset.unit != null)
            {
               Enum.TryParse(_asset.unit.name, true, out UnitType named);
               dataContainer.Units = new Unit(named, (Single)_asset.unit.meter);
            }

            dataContainer.Axis = (UpAxis)_asset.up_axis;
         }

         dataContainer.Metadata = metadata;
      }

      #endregion

      private bool IsEmpty()
      {
         if (dataContainer.Geometries.Count == 0 &&
             dataContainer.Animations.Count == 0 &&
             dataContainer.Controllers.Count == 0 &&
             dataContainer.Cameras.Count == 0 &&
             dataContainer.Lights.Count == 0 &&
             dataContainer.Materials.Count == 0 &&
             dataContainer.Effects.Count == 0 &&
             dataContainer.Images.Count == 0 &&
             dataContainer.VisualScenes.Count == 0)
         {
            return true;
         }
         return false;
      }
   }
}
