using System.Text;
using Adamantium.Core;
using Adamantium.UI.Markup.AST;

namespace Adamantium.UI.Markup.CodeGeneration;

public class AumlSourceGenerator : IAumlSourceGenerator
{
    public string Version => "1.0";
    
    private DefaultTypeContainer _defaultTypeContainer;
    
    private string _sourceGeneratorNotice => 
@$"// This code is automatically generated by AumlSourceGenerator version {Version}.
// Do not modify it if you don`t want to lose your changes";
    
    public void GenerateSourceCode(AumlMetadataContainer container, ICodeOutputSink output, IDiagnosticSink diagnostics)
    {
        container.SourceText = GenerateSources(container, diagnostics);
        output.Emit(container.ClassName, container.SourceText);
        container.TypeResolver.RegisterGeneratedType(new MetadataResolvedType(container));
    }
    
    public void GenerateResourceMap(ICodeOutputSink output, List<ResourceDictionaryInfo> collectedInfos)
    {
        var textGenerator = new TextGenerator();
        textGenerator.WriteLine("// <auto-generated/>");
        textGenerator.WriteLine("using System;");
        textGenerator.WriteLine("using System.Collections.Generic;");
        textGenerator.NewLine();
        textGenerator.WriteLine("namespace Adamantium.UI.Generated");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine("[Adamantium.UI.Core.Resources.ResourceMapRegistrar]");
        textGenerator.WriteLine("internal static partial class GeneratedResourceMap");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine("public static void Register(Dictionary<string, Type> map)");
        textGenerator.WriteOpenBraceAndIndent();

        foreach (var info in collectedInfos)
        {
            textGenerator.WriteLine($"map.Add(\"{info.Uri}\", typeof({info.FullTypeName}));");
        }

        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        output.Emit("GeneratedResourceMap", textGenerator.ToString());
    }

    public void GenerateAssemblyAttribute(ICodeOutputSink output)
    {
        var sb = new StringBuilder();
        sb.AppendLine(_sourceGeneratorNotice);
        sb.AppendLine("using Adamantium.UI.Core;");
        sb.AppendLine();
        sb.AppendLine("[assembly: Adamantium.UI.Core.Resources.ContainsResources]");

        output.Emit("Adamantium.UI.AssemblyAttributes", sb.ToString());
    }

    private string GenerateSources(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        return container.RootEntityType switch
        {
            EntityType.ResourceDictionary or EntityType.StyleSet => GenerateResourceFile(container, container.RootEntityType, diagnostics),
            EntityType.Theme => GenerateThemeFile(container, diagnostics),
            _ => GenerateControlFile(container, container.RootEntityType, diagnostics),
        };
    }

    private string GenerateThemeFile(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = $"{container.FileName}";
        var additionalPath = Path.GetDirectoryName(container.RelativeFilePath);
        var @namespace = $"{container.AssemblyName}";
        if (!string.IsNullOrEmpty(additionalPath))
        {
            additionalPath = additionalPath.ToNamespace();
            @namespace = $"{@namespace}.{additionalPath}";
        }
        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.WriteLine($"using {container.AssemblyName};");

        var themeName = string.Empty;


        if (string.IsNullOrEmpty(themeName))
        {
            themeName = className;
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($@"public {className}() : base(""{themeName}"")");
        textGenerator.WriteOpenBraceAndIndent();
        
        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, EntityType.Theme);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, true);

        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateResourceFile(
        AumlMetadataContainer container, 
        EntityType entityType,
        IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = container.FileName;
        var additionalPath = Path.GetDirectoryName(container.RelativeFilePath);
        var @namespace = $"{container.AssemblyName}";
        if (!string.IsNullOrEmpty(additionalPath))
        {
            additionalPath = additionalPath.ToNamespace();
            @namespace = $"{@namespace}.{additionalPath}";
        }
        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();

        int id = 1;
        if (entityType == EntityType.StyleSet)
        {
            var type = container.DefaultTypeContainer.ITheme;
            textGenerator.WriteLine($"protected override void OnInitialize({type.FullName} theme)");
        }
        else
        {
            textGenerator.WriteLine($"protected override void OnInitialize()");
        }

        textGenerator.WriteOpenBraceAndIndent();
        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, entityType);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, true);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateControlFile(AumlMetadataContainer container, EntityType entityType, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var directives = rootNode.Children.Where(x => x is AumlAstDirective).ToList();
        string className = container.FileName;
        string @namespace = String.Empty;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.GetTypeByFullName(rootNode.TypeReference.GetFullTypeName());

        AumlAstDirective classDirective = null;
        foreach (var aumlAstNode in directives)
        {
            var directive = (AumlAstDirective)aumlAstNode;
            if (directive.Name == AumlDirectives.Namespace)
            {
                classDirective = directive;
                break;
            }
        }
        
        var directiveValue = classDirective.Value as AumlAstTextNode;
        @namespace = directiveValue.Text;
        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public class {container.RootClassName} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();

        int id = 1;
        foreach (var item in container.NamedElements)
        {
            typeContainer = container.TypeResolver.GetResolvedAssembly(item.Element.TypeReference.Assembly);
            var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == item.Element.TypeReference.Name);
            textGenerator.WriteLine($"{typeInfo.FullName} {item.Name};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"protected override void InitializeComponent()");
        textGenerator.WriteOpenBraceAndIndent();

        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, entityType);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, false);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }
}