using Adamantium.Core;
using Adamantium.UI.Markup.AST;
using Adamantium.UI.Markup.AST.MarkupExtension;

namespace Adamantium.UI.Markup.CodeGeneration;

public class AumlSourceGenerator : IAumlSourceGenerator
{
    public string Version => "1.0";
    
    private DefaultTypeContainer _defaultTypeContainer;
    
    private string _sourceGeneratorNotice => 
@$"// This code is automatically generated by AumlSourceGenerator version {Version}.
// Do not modify it if you don`t want to lose your changes";
    
    public void GenerateSourceCode(AumlMetadataContainer container, ICodeOutputSink output, IDiagnosticSink diagnostics)
    {
        container.SourceText = GenerateSources(container, diagnostics);
        output.Emit(container.ClassName, container.SourceText);
    }

    private string GenerateSources(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        return container.RootEntityType switch
        {
            EntityType.ResourceDictionary or EntityType.StyleSet => GenerateResourceFile(container, container.RootEntityType, diagnostics),
            EntityType.Theme => GenerateThemeFile(container, diagnostics),
            _ => GenerateControlFile(container, container.RootEntityType, diagnostics),
        };
    }

    private string GenerateThemeFile(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = $"{container.FileName}";
        var @namespace = $"{container.RootNamespace}";
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.WriteLine($"using {container.RootNamespace}.GeneratedResources;");

        var element = container.RootNode as AumlAstObjectNode;
        var properties = element.GetProperties();
        var themeName = string.Empty;
        List<AumlAstPropertyNode> resourceDictionaries = [];
        List<AumlAstObjectNode> styleSets = [];

        foreach (var prop in properties)
        {
            var propertyRef = prop.Property as AumlAstPropertyReference;
            if (propertyRef.Name == "Resources")
            {
                resourceDictionaries = prop.Values[0].GetResourceDictionaries().ToList();
            }
            else if (propertyRef.Name == "StyleSets")
            {
                foreach (var value in prop.Values)
                {
                    if (value is AumlAstObjectNode node)
                    {
                        styleSets.Add(node);
                    }
                }
            }
            else if (propertyRef.Name == "Name")
            {
                themeName = ((AumlAstTextNode)prop.Values[0]).Text;
            }
        }

        if (string.IsNullOrEmpty(themeName))
        {
            themeName = className;
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($@"public {className}() : base(""{themeName}"")");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($"{container.DefaultTypeContainer.ResourceDictionary.FullName} resource = null;");
        foreach (var r in resourceDictionaries)
        {
            textGenerator.WriteLine(
                            $"resource = new {Path.GetFileNameWithoutExtension(r.Values[0].ToString())}();");
            textGenerator.WriteLine("resource.Initialize();");
            textGenerator.WriteLine("Resources.MergedDictionaries.Add(resource);");
        }

        textGenerator.WriteLine($"{container.DefaultTypeContainer.StyleSet.FullName} styleSet = null;");
        foreach (var r in styleSets)
        {
            var props = r.GetProperties();

            foreach (var p in props)
            {
                if (p.Property is AumlAstPropertyReference { Name: "Source" })
                {
                    textGenerator.WriteLine(
                        $"styleSet = new {Path.GetFileNameWithoutExtension(p.Values[0].ToString())}();");
                    textGenerator.WriteLine("styleSet.Initialize(this);");
                    textGenerator.WriteLine("StyleSets.Add(styleSet);");
                }
            }
        }

        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateResourceFile(AumlMetadataContainer container, 
        EntityType entityType,
        IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = container.FileName;
        var @namespace = $"{container.RootNamespace}.GeneratedResources";
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($"public {className}()");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($@"Source = new Uri(@""{container.RelativeFilePath}"", UriKind.Relative);");
        textGenerator.UnindentAndWriteCloseBrace();

        int id = 1;
        if (entityType == EntityType.StyleSet)
        {
            var type = container.DefaultTypeContainer.ITheme;
            textGenerator.WriteLine($"protected override void OnInitialize({type.FullName} theme)");
        }
        else
        {
            textGenerator.WriteLine($"protected override void OnInitialize()");
        }

        textGenerator.WriteOpenBraceAndIndent();
        ProcessResource(entityType, className, container, container.RootNode, diagnostics, textGenerator, ref id);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateControlFile(AumlMetadataContainer container, EntityType entityType, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var directives = rootNode.Children.Where(x => x is AumlAstDirective).ToList();
        string className = container.FileName;
        string @namespace = String.Empty;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.GetTypeByFullName(rootNode.TypeReference.GetFullTypeName());

        AumlAstDirective classDirective = null;
        foreach (var aumlAstNode in directives)
        {
            var directive = (AumlAstDirective)aumlAstNode;
            if (directive.Name == AumlDirectives.Namespace)
            {
                classDirective = directive;
                break;
            }
        }
        
        var directiveValue = classDirective.Value as AumlAstTextNode;
        @namespace = directiveValue.Text;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public class {container.RootClassName} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();

        int id = 1;
        foreach (var item in container.NamedElements)
        {
            typeContainer = container.TypeResolver.GetResolvedAssembly(item.Element.TypeReference.Assembly);
            var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == item.Element.TypeReference.Name);
            textGenerator.WriteLine($"{typeInfo.FullName} {item.Name};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"protected override void InitializeComponent()");
        textGenerator.WriteOpenBraceAndIndent();

        ProcessControlElements(string.Empty, className, container, container.RootNode, diagnostics, textGenerator, ref id);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string ProcessControlElements(
        string parentName, 
        string className,
        AumlMetadataContainer container, 
        IAumlAstNode currentNode,
        IDiagnosticSink diagnostics,
        TextGenerator textGenerator, ref int id)
    {
        var element = currentNode as AumlAstObjectNode;
        string elementName = string.Empty;

        var typeContainer = container.TypeResolver.GetResolvedAssembly(element.TypeReference.Assembly);
        var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == element.TypeReference.Name);
        var properties = element.GetProperties();
        var objects = element.GetLogicalChildrenObjects();

        // Create element instance using new
        if (element != container.RootNode)
        {
            if (container.NamedElementsMap.TryGetValue(element, out var name))
            {
                elementName = name;
                textGenerator.WriteLine($"{elementName} = new {typeInfo.FullName}();");
            }
            else
            {
                elementName = $"element_{id}";
                textGenerator.WriteLine($"var {elementName} = new {typeInfo.FullName}();");
                id++;
            }
        }

        // Apply properties to current control instance
        foreach (var prop in properties)
        {
            var propertyRef = prop.Property as AumlAstPropertyReference;

            if (propertyRef.IsAttachedProperty)
            {
                var types = container.TypeResolver.GetResolvedAssembly(propertyRef.OwnerType.Assembly);
                var attachedTypeInfo = types.Types.FirstOrDefault(x => x.Name == propertyRef.OwnerType.Name);
                //var symbolInfo = typeInfo.GetMemberByName(propertyRef.Name);
                //if (symbolInfo.Kind == SymbolKind.Property)
                {
                    textGenerator.WriteLine(
                        $"{propertyRef.OwnerType.GetFullTypeName()}.Set{propertyRef.Name}({elementName}, {prop.GetTextValue()});");
                }
            }
            else
            {
                var resolvedMember = typeInfo.GetMemberByName(propertyRef.Name);
                if (resolvedMember == null)
                {
                    diagnostics.ReportError(className, $"There is no property named {propertyRef.Name} in {className}");
                    continue;
                }

                string symbolName = string.Empty;

                symbolName = string.IsNullOrEmpty(elementName) ? propertyRef.Name : $"{elementName}.{propertyRef.Name}";

                if (resolvedMember.MemberKind == ResolvedMemberKind.Event)
                {
                    if (prop.Values.Count != 1)
                    {
                        // Here we need to throw exception because we cannot have more than 1 subscription per 1 event for one property
                        break;
                    }
                    else
                    {
                        textGenerator.WriteLine($"{symbolName} += {prop.GetTextValue()};");
                    }
                }
                else if (resolvedMember.MemberKind == ResolvedMemberKind.Property)
                {
                    var objectNodes = new List<IAumlAstValueNode>();
                    foreach (var value in prop.Values)
                    {
                        if (value.IsTextNode()) // Value is simple text
                        {
                            GenerateCodeForMember(container, symbolName, prop, value, resolvedMember, textGenerator);
                        }
                        else // Value is Object node
                        {
                            objectNodes.Add(value);
                        }
                    }

                    foreach (var objectNode in objectNodes)
                    {
                        if (objectNode is AumlAstObjectNode)
                        {
                            var name = ProcessControlElements(elementName, 
                                className, 
                                container, 
                                objectNode,
                                diagnostics,
                                textGenerator, ref id);

                            textGenerator.WriteLine($"{symbolName} = {name};");
                        }
                    }
                }
            }
        }

        // Process child controls
        foreach (var obj in objects)
        {
            var controlName =
                ProcessControlElements(elementName, className, container, obj, diagnostics, textGenerator, ref id);

            var isIContainer = typeInfo.ImplementsInterface("IContainer");

            if (isIContainer)
            {
                var containerType = typeInfo.GetInterface("IContainer");
                textGenerator.WriteLine(!string.IsNullOrEmpty(elementName)
                    ? $"(({containerType.FullName}){elementName}).AddOrSetChildComponent({controlName});"
                    : $"(({containerType.FullName})this).AddOrSetChildComponent({controlName});");
            }
            else
            {
                if (typeInfo.FindPropertyWithAttribute("ContentAttribute", out var property))
                {
                    var isCollection = property.PropertyType.ImplementsInterface("ICollection") || property.PropertyType.ImplementsInterface("IList");
                    if (isCollection)
                    {
                        textGenerator.WriteLine(!string.IsNullOrEmpty(elementName)
                            ? $"{elementName}.{property.Name}.Add({controlName});"
                            : $"{property.Name}.Add({controlName});");
                    }
                    else
                    {
                        textGenerator.WriteLine(!string.IsNullOrEmpty(elementName)
                            ? $"{elementName}.{property.Name} = {controlName};"
                            : $"{property.Name} = {controlName};");
                    }
                }
            }
        }

        return elementName;
    }

    private string ProcessMarkupExtension(
        string className,
        AumlMetadataContainer container,
        IAumlAstNode currentNode,
        IDiagnosticSink diagnostics,
        TextGenerator textGenerator,
        ref int id)
    {
        switch (currentNode)
        {
            case AumlAstMarkupExtensionLiteral literal:
            {
                var typeContainer = container.TypeResolver.GetResolvedAssembly(literal.TypeReference.Assembly);
                var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == literal.TypeReference.Name);
                var literalName = $"element_{id}";
                textGenerator.WriteLine($"var {literalName} = new {typeInfo.FullName}();");
                id++;
                return literalName;
            }
            case AumlAstMarkupExtensionNode extensionNode:
            {
                var typeContainer = container.TypeResolver.GetResolvedAssembly(extensionNode.TypeReference.Assembly);
                var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == extensionNode.TypeReference.Name);
                var elementName = $"element_{id}";
                id++;
                if (typeInfo.FullName == container.DefaultTypeContainer.ResourceReference.FullName && extensionNode.Arguments.Count == 1)
                {
                    textGenerator.WriteLine($"var {elementName} = new {typeInfo.FullName}(\"{extensionNode.Arguments.First()}\");");
                    return elementName;
                }
                
                textGenerator.WriteLine($"var {elementName} = new {typeInfo.FullName}();");
                
                foreach (var argument in extensionNode.Arguments)
                {
                    var propertyInfo = typeInfo.GetMemberByName(argument.Name);

                    if (propertyInfo == null)
                    {
                        diagnostics.ReportError(className, $"Cannot resolve property '{argument.Name}' for markup extension {typeInfo.FullName}");
                        continue;
                    }

                    var target = $"{elementName}.{argument.Name}";

                    if (argument.Value.IsTextNode())
                    {
                        GenerateCodeForMember(container, target, null, argument.Value, propertyInfo, textGenerator);
                    }
                    else if (argument.Value is AumlAstObjectNode or AumlAstMarkupExtensionNode or AumlAstMarkupExtensionLiteral)
                    {
                        var nestedValue = ProcessMarkupExtension(className, container, argument.Value, diagnostics, textGenerator, ref id);
                        textGenerator.WriteLine($"{target} = {nestedValue};");
                    }
                }
                return elementName;
            }
        }
        
        return string.Empty;
    }

    private string ProcessResource(
        EntityType entityType,
        string className,
        AumlMetadataContainer container,
        IAumlAstNode currentNode,
        IDiagnosticSink diagnostics,
        TextGenerator textGenerator,
        ref int id)
    {
        // TODO: here currentNode could be a TemplateNode. Need to process it correctly

        var element = currentNode as AumlAstObjectNode;
        var directives = element.Children.Where(x => x is AumlAstDirective).ToList();
        string key = string.Empty;
        foreach (var aumlAstNode in directives)
        {
            var directive = (AumlAstDirective)aumlAstNode;
            if (directive.Name == AumlDirectives.Key)
            {
                var textNode = directive.Value as AumlAstTextNode;
                key = textNode.Text;
                break;
            }
        }

        string elementName = string.Empty;

        var typeContainer = container.TypeResolver.GetResolvedAssembly(element.TypeReference.Assembly);
        var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == element.TypeReference.Name);
        var properties = element.GetProperties();
        var objects = element.GetLogicalChildrenObjects();

        if (element != container.RootNode)
        {
            elementName = $"element_{id}";
            textGenerator.WriteLine($"var {elementName} = new {typeInfo.FullName}();");
            id++;
        }

        foreach (var prop in properties)
        {
            var propertyRef = prop.Property as AumlAstPropertyReference;

            if (propertyRef.IsAttachedProperty)
            {
                var types = container.TypeResolver.GetResolvedAssembly(propertyRef.OwnerType.Assembly);
                var attachedTypeInfo = types.Types.FirstOrDefault(x => x.Name == propertyRef.OwnerType.Name);
                textGenerator.WriteLine(
                    $"{attachedTypeInfo.FullName}.Set{propertyRef.Name}({elementName}, {prop.GetTextValue()});");
            }
            else
            {
                var resolvedMember = typeInfo.GetMemberByName(propertyRef.Name);
                if (resolvedMember == null)
                {
                    diagnostics.ReportError(className, $"There is no property named {propertyRef.Name} in {className}");
                    continue;
                }

                var symbolName = string.IsNullOrEmpty(elementName)
                    ? propertyRef.Name
                    : $"{elementName}.{propertyRef.Name}";

                if (resolvedMember.MemberKind == ResolvedMemberKind.Event)
                {
                    if (prop.Values.Count != 1)
                    {
                        // Here we need to throw exception because we cannot have more than 1 subscription per 1 event for one property
                        break;
                    }
                    else
                    {
                        textGenerator.WriteLine($"{symbolName} += {prop.GetTextValue()};");
                    }
                }
                else if (resolvedMember.MemberKind == ResolvedMemberKind.Property)
                {
                    var objectNodes = new List<IAumlAstValueNode>();
                    foreach (var value in prop.Values)
                    {
                        if (value.IsTextNode()) // Value is simple text
                        {
                            GenerateCodeForMember(container, symbolName, prop, value, resolvedMember, textGenerator);
                        }
                        else // Value is Object node
                        {
                            objectNodes.Add(value);
                        }
                    }

                    foreach (var objectNode in objectNodes)
                    {
                        if (objectNode is AumlAstObjectNode)
                        {
                            var name = ProcessResource(entityType, className, container, objectNode, diagnostics,
                                textGenerator, ref id);

                            textGenerator.WriteLine($"{symbolName} = {name};");
                        }
                        else if (objectNode is AumlAstMarkupExtensionNode or AumlAstMarkupExtensionLiteral)
                        {
                            var name = ProcessMarkupExtension(className, container, objectNode, diagnostics,
                                textGenerator, ref id);

                            textGenerator.WriteLine($"{symbolName} = {name};");
                        }
                    }
                }
            }
        }

        foreach (var obj in objects)
        {
            var name = ProcessResource(entityType, className, container, obj, diagnostics, textGenerator, ref id);

            if (container.ClassName == "ButtonStyleSet")
            {
                int x = 0;
            }

            if (entityType == EntityType.StyleSet)
            {
                if (element.TypeReference.Name == "Style")
                {
                    textGenerator.WriteLine($"{elementName}.Add({name});");
                }
                else
                {
                    textGenerator.WriteLine($"Add({name});");
                }
            }
        }

        if (!string.IsNullOrEmpty(key))
        {
            textGenerator.WriteLine($@"Add(""{key}"", {elementName});");
        }

        return elementName;
    }

    private void GenerateCodeForMember(
        AumlMetadataContainer container,
        string symbolName, 
        AumlAstPropertyNode property, 
        IAumlAstValueNode value,
        IResolvedMember member, 
        TextGenerator textGenerator)
    {
        var type = member.MemberType;
        switch (type.SpecialType)
        {
            case ResolvedSpecialType.None:
                if (type.TypeKind == ResolvedTypeKind.Enum)
                {
                    textGenerator.WriteLine($@"{symbolName} = {type.FullName}.{property.GetTextValue()};");
                }
                else
                {
                    switch (type.Name)
                    {
                        case "Template":
                        {
                            var templateNode = value as AumlAstTemplateNode;
                            textGenerator.WriteLine($"{symbolName} = ControlTemplate.Load({templateNode.TemplateContent})");
                            break;
                        }
                        default:
                            textGenerator.WriteLine(
                                $@"{symbolName} = {container.DefaultTypeContainer.TypeParser.FullName}.Parse<{type.FullName}>(""{property.GetTextValue()}"");");
                            break;
                    }
                }
                break;
            case ResolvedSpecialType.System_Enum:
                textGenerator.WriteLine($@"{symbolName} = {type.FullName}.{property.GetTextValue()};");
                break;
            case ResolvedSpecialType.System_Object:
            case ResolvedSpecialType.System_String:
                if (property.IsSetter() && property.GetTextValue() == "Template")
                {
                    if (container.FileName.StartsWith("ButtonStyleSet"))
                    {
                        int x = 0;
                    }
                }
                else
                {
                    textGenerator.WriteLine($@"{symbolName} = ""{property.GetTextValue()}"";");
                }
                break;
            default:
                textGenerator.WriteLine($@"{symbolName} = {property.GetTextValue().ToLower()};");
                break;
        }
    }
}