using System.Text;
using Adamantium.Core;
using Adamantium.UI.Markup.AST;

namespace Adamantium.UI.Markup.CodeGeneration;

public class AumlSourceGenerator : IAumlSourceGenerator
{
    public string Version => "1.0";
    
    private DefaultTypeContainer _defaultTypeContainer;
    
    private string _sourceGeneratorNotice => 
@$"// This code is automatically generated by AumlSourceGenerator version {Version}.
// Do not modify it if you don`t want to lose your changes";
    
    public void GenerateSourceCode(AumlMetadataContainer container, ICodeOutputSink output, IDiagnosticSink diagnostics)
    {
        container.SourceText = GenerateSources(container, diagnostics);
        output.Emit(container.ClassName, container.SourceText);
        container.TypeResolver.RegisterGeneratedType(new MetadataResolvedType(container));
    }
    
    public void GenerateResourceMap(ICodeOutputSink output, List<ResourceDictionaryInfo> collectedInfos)
    {
        var textGenerator = new TextGenerator();
        textGenerator.WriteLine("// <auto-generated/>");
        textGenerator.WriteLine("using System;");
        textGenerator.WriteLine("using System.Collections.Generic;");
        textGenerator.NewLine();
        textGenerator.WriteLine("namespace Adamantium.UI.Generated");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine("[Adamantium.UI.Core.Resources.ResourceMapRegistrar]");
        textGenerator.WriteLine("internal static partial class GeneratedResourceMap");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine("public static void Register(Dictionary<string, Type> map)");
        textGenerator.WriteOpenBraceAndIndent();

        foreach (var info in collectedInfos)
        {
            textGenerator.WriteLine($"map.Add(\"{info.Uri}\", typeof({info.FullTypeName}));");
        }

        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        output.Emit("GeneratedResourceMap", textGenerator.ToString());
    }

    public void GenerateAssemblyAttribute(ICodeOutputSink output)
    {
        var sb = new StringBuilder();
        sb.AppendLine(_sourceGeneratorNotice);
        sb.AppendLine("using Adamantium.UI.Core;");
        sb.AppendLine();
        sb.AppendLine("[assembly: Adamantium.UI.Core.Resources.ContainsResources]");

        output.Emit("Adamantium.UI.AssemblyAttributes", sb.ToString());
    }

    private string GenerateSources(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        return container.RootEntityType switch
        {
            EntityType.ResourceDictionary or EntityType.StyleSet => GenerateResourceFile(container, container.RootEntityType, diagnostics),
            EntityType.Theme => GenerateThemeFile(container, diagnostics),
            _ => GenerateControlFile(container, container.RootEntityType, diagnostics),
        };
    }

    private string GenerateThemeFile(AumlMetadataContainer container, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = $"{container.FileName}";
        var additionalPath = Path.GetDirectoryName(container.RelativeFilePath);
        var @namespace = $"{container.AssemblyName}";
        if (!string.IsNullOrEmpty(additionalPath))
        {
            additionalPath = additionalPath.ToNamespace();
            @namespace = $"{@namespace}.{additionalPath}";
        }
        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.WriteLine($"using {container.AssemblyName};");

        var themeName = string.Empty;


        if (string.IsNullOrEmpty(themeName))
        {
            themeName = className;
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();
        textGenerator.WriteLine($@"public {className}() : base(""{themeName}"")");
        textGenerator.WriteOpenBraceAndIndent();
        
        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, EntityType.Theme);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, true);

        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateResourceFile(
        AumlMetadataContainer container, 
        EntityType entityType,
        IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.Types.FirstOrDefault(x => x.Name == rootNode.TypeReference.Name);
        var className = container.FileName;
        var additionalPath = Path.GetDirectoryName(container.RelativeFilePath);
        var @namespace = $"{container.AssemblyName}";
        if (!string.IsNullOrEmpty(additionalPath))
        {
            additionalPath = additionalPath.ToNamespace();
            @namespace = $"{@namespace}.{additionalPath}";
        }
        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public sealed class {className} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();

        int id = 1;
        if (entityType == EntityType.StyleSet)
        {
            var type = container.DefaultTypeContainer.ITheme;
            textGenerator.WriteLine($"protected override void OnInitialize({type.FullName} theme)");
        }
        else
        {
            textGenerator.WriteLine($"protected override void OnInitialize()");
        }

        textGenerator.WriteOpenBraceAndIndent();
        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, entityType);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, true);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }

    private string GenerateControlFile(AumlMetadataContainer container, EntityType entityType, IDiagnosticSink diagnostics)
    {
        var rootNode = container.RootNode as AumlAstObjectNode;
        string className = container.FileName;
        var typeContainer = container.TypeResolver.GetResolvedAssembly(rootNode.TypeReference.Assembly);
        var rootBaseType = typeContainer.GetTypeByFullName(rootNode.TypeReference.GetFullTypeName());

        // Namespace: an explicit x:Namespace directive (the WPF x:Class analog) takes priority; otherwise derive it
        // from AssemblyName + relative path. Shared with the pre-registration pass so a cross-referenced view resolves
        // to the exact name it is generated under.
        var @namespace = AumlNaming.ComputeNamespace(container.RelativeFilePath, container.AssemblyName, rootNode, className);

        container.Namespace = @namespace;
        container.ClassName = className;

        var textGenerator = new TextGenerator();
        textGenerator.WriteLine(_sourceGeneratorNotice);

        foreach (var ns in container.Usings)
        {
            textGenerator.WriteLine($"using {ns};");
        }

        textGenerator.NewLine();

        textGenerator.WriteLine($"namespace {@namespace};");
        textGenerator.NewLine();
        textGenerator.WriteLine($"public class {container.RootClassName} : {rootBaseType.FullName}");
        textGenerator.WriteOpenBraceAndIndent();

        int id = 1;
        foreach (var item in container.NamedElements)
        {
            typeContainer = container.TypeResolver.GetResolvedAssembly(item.Element.TypeReference.Assembly);
            var typeInfo = typeContainer.Types.FirstOrDefault(x => x.Name == item.Element.TypeReference.Name);
            // A NAMED element held back by x:Load has no field to hold it - it does not exist yet. What the name means
            // instead is "give it to me", and asking builds it: in UWP the field is simply null until something loads
            // the element, and everyone trips over that.
            if (CodeGenerationContext.GetLoadDirective(item.Element) != null)
            {
                // PUBLIC, unlike the plain name fields: this one exists to be CALLED FROM OUTSIDE. A view has no code
                // behind it - it is extended through behaviors - so a private accessor would leave x:Load="False" with
                // no way to be asked for at all.
                var slotField = CodeGenerationContext.LoadSlotField(item.Name);
                textGenerator.WriteLine($"global::Adamantium.UI.Controls.LoadSlot {slotField};");
                textGenerator.WriteLine($"public {typeInfo.FullName} {item.Name} => ({typeInfo.FullName}){slotField}.Element;");
                continue;
            }

            textGenerator.WriteLine($"{typeInfo.FullName} {item.Name};");
        }

        textGenerator.NewLine();

        if (!string.IsNullOrEmpty(container.RootViewModelTypeName))
        {
            // x:ViewModel: declare the view-model type as metadata. The framework resolves an instance from the app's
            // dependency resolver and assigns it as DataContext when the view goes live (FundamentalUIComponent.ApplyViewModel).
            textGenerator.WriteLine($"public override global::System.Type ViewModelType => typeof(global::{container.RootViewModelTypeName});");
            textGenerator.NewLine();
        }

        if (!string.IsNullOrEmpty(container.RootKeepAlive))
        {
            // x:KeepAlive: what the view asks of whoever navigates away from it. Metadata only - the view parks nothing
            // itself.
            textGenerator.WriteLine("public override global::Adamantium.UI.Core.NavigationCacheMode KeepAlive => " +
                $"global::Adamantium.UI.Core.NavigationCacheMode.{container.RootKeepAlive};");
            textGenerator.NewLine();
        }

        textGenerator.WriteLine($"protected override void InitializeComponent()");
        textGenerator.WriteOpenBraceAndIndent();

        var codeGenerationContext = new CodeGenerationContext(textGenerator, container, entityType);
        codeGenerationContext.ProcessControlElements((AumlAstObjectNode)container.RootNode, diagnostics, false);
        textGenerator.UnindentAndWriteCloseBrace();
        textGenerator.UnindentAndWriteCloseBrace();

        return textGenerator;
    }
}