<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.13.2" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Adamantium.Engine\Adamantium.Engine.csproj" />
        <ProjectReference Include="..\..\Adamantium.XInput\Adamantium.XInput.csproj" />
        <ProjectReference Include="..\..\Adamantium.GameInput\Adamantium.GameInput.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\Adamantium.FontTests\TTFFonts\SourceSans3-Regular.ttf" Link="Fonts\SourceSans3-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="..\Adamantium.FontTests\OTFFonts\SourceSans3-Regular.otf" Link="Fonts\SourceSans3-Regular.otf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
