using System;
using System.Collections.Generic;
using Adamantium.Engine.Compiler.Converter.AutoGenerated;
using Adamantium.Engine.Compiler.Models.ConversionUtils;
using Adamantium.Engine.Core.Models;

namespace Adamantium.Engine.Compiler.Converter.Containers
{
   public class ColladaDataContainer : DataContainer
   {
      public ColladaDataContainer(String filePath) : base(filePath)
      {
         VisualScenes = new List<visual_scene>();
         Geometries = new List<geometry>();
         Animations = new List<animation>();
         Controllers = new List<controller>();
         Images = new List<image>();
         Lights = new List<light>();
         Materials = new List<material>();
         Cameras = new List<camera>();
         Effects = new List<effect>();
         Axis = new UpAxis();
      }


      //коллекция геометрий
      public List<geometry> Geometries { get; set; }
      //коллекция узлов визуальной сцены
      public List<visual_scene> VisualScenes { get; set; }
      //коллекция анимаций
      public List<animation> Animations { get; set; }
      //коллекция контроллеров
      public List<controller> Controllers { get; set; }
      //коллекция изображений
      public List<image> Images { get; set; }
      //коллекция света
      public List<light> Lights { get; set; }
      //коллекция материалов
      public List<material> Materials { get; set; }
      //коллекция камер
      public List<camera> Cameras { get; set; }
      //коллекция эффектов
      public List<effect> Effects { get; set; }
      //Напраление осей
      public UpAxis Axis { get; set; }
      //Единицы измерения меша относительно общей системы координат
      public SceneData.Unit Units { get; set; }

      public override FileType Type => FileType.Collada;
   }
}
