using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Adamantium.Engine.Compiler.Converter.AutoGenerated;
using Adamantium.Engine.Compiler.Converter.Configs;
using Adamantium.Graphics.Core;
using Adamantium.Graphics.Core.Models;
using Adamantium.Mathematics;
using LightType = Adamantium.Graphics.Core.Models.LightType;

namespace Adamantium.Engine.Compiler.Models.ConversionUtils
{
    internal partial class ColladaConversionExecutor : ConversionExecutorBase
    {
        private const String PositionSemantic = "VERTEX";
        private const String RawPositionSemantic = "POSITION";

        private static readonly char[] WhiteSpace = { ' ', '\t', '\r', '\n' };

        /// <summary>What the file has that the parse cannot do - so the loss does not pass in silence.</summary>
        public List<String> UnsupportedFeatures { get; } = new();

        //Geometries are parsed in parallel and all of them write here
        private void ReportUnsupported(String feature)
        {
            lock (UnsupportedFeatures) UnsupportedFeatures.Add(feature);
        }

        private static int MaxOffset(InputLocalOffset[] inputs)
        {
            var max = 0;
            if (inputs != null)
            {
                foreach (var input in inputs)
                {
                    if ((int)input.offset > max) max = (int)input.offset;
                }
            }
            return max;
        }

        /// <summary>The id out of a "#id" reference. A reference into another document ("file.dae#id") is beyond
        /// us, but silently chopping its first character is not the answer either.</summary>
        private static String Source(String url)
        {
            if (String.IsNullOrEmpty(url)) return String.Empty;

            var hash = url.LastIndexOf('#');
            return hash >= 0 ? url.Substring(hash + 1) : url;
        }
        private const String NormalSemantic = "NORMAL";
        private const String UVSemantic = "TEXCOORD";
        private const String ColorSemantic = "COLOR";

        private const String AnimationInputSemantic = "INPUT";
        private const String AnimationOutputSemantic = "OUTPUT";
        private const String AnimationInterpolationSemantic = "INTERPOLATION";

        private const String ControllerJointSemantic = "JOINT";
        private const String ControllerWeightSemantic = "WEIGHT";
        private const String ControllerInvBindMatrixSemantic = "INV_BIND_MATRIX";

        public ColladaConversionExecutor(ConversionConfig config, UpAxis upAxis) : base(config, upAxis)
        {
        }

        #region Geometry

        internal SceneData.Model ConstructMesh(SceneData container, List<IndicesContainer> indicesContainers, Mesh mesh, String meshId, String meshName)
        {
            SceneData.Model constructedMesh = container.GetModelByID(meshId);

            if (constructedMesh == null)
            {
                constructedMesh = container.CreateMesh(container.Models, meshId, meshName);
            }
            
            foreach (var indicesContainer in indicesContainers)
            {
                // Without indices there is nothing to assemble. AssemblePoints on an empty list used to silently
                // leave the RAW vertex set from <source>, and a triangle soup of every point arrived in the scene.
                if (indicesContainer.Positions.Count == 0)
                {
                    continue;
                }

                var finalMesh = mesh.Clone();
                finalMesh.MeshTopology = indicesContainer.MeshTopology;
                var semantic = indicesContainer.Semantic;
                //Vertices are reordered the way the faces name them, not the way the file stores them - so a
                //coordinate set may well repeat
                finalMesh.AssemblePoints(indicesContainer.Positions);
                finalMesh.GenerateBasicIndices();

                if (semantic.HasFlag(VertexSemantic.Normal))
                {
                    finalMesh.AssembleNormals(indicesContainer.Normals);
                }

                if (semantic.HasFlag(VertexSemantic.UV0))
                {
                    finalMesh.AssembleUVs(indicesContainer.UV0, 0);
                }

                if (semantic.HasFlag(VertexSemantic.UV1))
                {
                    finalMesh.AssembleUVs(indicesContainer.UV1, 1);
                }

                if (semantic.HasFlag(VertexSemantic.UV2))
                {
                    finalMesh.AssembleUVs(indicesContainer.UV2, 2);
                }

                if (semantic.HasFlag(VertexSemantic.UV3))
                {
                    finalMesh.AssembleUVs(indicesContainer.UV3, 3);
                }

                if (semantic.HasFlag(VertexSemantic.Color))
                {
                    finalMesh.AssembleColors(indicesContainer.Colors);
                }

                if (finalMesh.Semantic.HasFlag(VertexSemantic.JointIndices) && finalMesh.Semantic.HasFlag(VertexSemantic.JointWeights))
                {
                    finalMesh.AssembleBones(indicesContainer.Positions);
                }

                constructedMesh.Meshes.Add(finalMesh);
            }
            return constructedMesh;
        }

        public Mesh GetRawMesh(geometry geometry, Dictionary<String, VertexSemantic> semanticIdMapping, out String meshId, out String name)
        {
            var rawMesh = new Mesh();
            SceneData.GeometryData rawGeometryData = new SceneData.GeometryData();
            var tmp = new Vector3();
            Vector2F tmpTexture = new Vector2F();
            meshId = geometry.id;
            name = geometry.name;
            var mesh = geometry.Item as mesh;

            if (mesh != null)
            {
                foreach (var source in mesh.source)
                {
                    var floatArray = source.Item as float_array;
                    if (floatArray != null)
                    {
                        if (semanticIdMapping.ContainsKey(source.id))
                        {
                            VertexSemantic tempSemantic = semanticIdMapping[source.id];
                            int stride = (int)source.technique_common.accessor.stride;
                            switch (tempSemantic)
                            {
                                case VertexSemantic.Position:
                                    for (int i = 0; i < floatArray.Values.Length; i += stride)
                                    {
                                        //for (int j = 0; j < stride; j++)
                                        {
                                            tmp.X = (float)floatArray.Values[i];
                                            tmp.Y = (float)floatArray.Values[i + 1];
                                            tmp.Z = (float)floatArray.Values[i + 2];
                                            rawGeometryData.Positions.Add(tmp);
                                        }
                                    }
                                    break;
                                // Normals from the file. They were not read at all, and the mesh then re-derived
                                // them by averaging - erasing the hard edges they were authored for.
                                case VertexSemantic.Normal:
                                    for (int i = 0; i < floatArray.Values.Length; i += stride)
                                    {
                                        rawGeometryData.Normals.Add(new Vector3F(
                                           (float)floatArray.Values[i],
                                           (float)floatArray.Values[i + 1],
                                           (float)floatArray.Values[i + 2]));
                                    }
                                    break;
                                case VertexSemantic.UV0:
                                case VertexSemantic.UV1:
                                case VertexSemantic.UV2:
                                case VertexSemantic.UV3:
                                    for (int i = 0; i < floatArray.Values.Length; i += stride)
                                    {
                                        //for (int j = 0; j < stride; j++)
                                        {
                                            tmpTexture.X = (float)floatArray.Values[i];
                                            tmpTexture.Y = (float)floatArray.Values[i + 1];
                                            switch (tempSemantic)
                                            {
                                                case VertexSemantic.UV0:
                                                    rawGeometryData.UV0.Add(tmpTexture);
                                                    break;
                                                case VertexSemantic.UV1:
                                                    rawGeometryData.UV1.Add(tmpTexture);
                                                    break;
                                                case VertexSemantic.UV2:
                                                    rawGeometryData.UV2.Add(tmpTexture);
                                                    break;
                                                case VertexSemantic.UV3:
                                                    rawGeometryData.UV3.Add(tmpTexture);
                                                    break;
                                            }

                                        }
                                    }
                                    break;
                                case VertexSemantic.Color:
                                    for (int i = 0; i < floatArray.Values.Length; i += stride)
                                    {
                                        //for (int j = 0; j < stride; j++)
                                        {
                                            var color = new Vector4F(
                                               (float)floatArray.Values[i],
                                               (float)floatArray.Values[i + 1],
                                               (float)floatArray.Values[i + 2],
                                               (float)floatArray.Values[i + 3]);
                                            rawGeometryData.Colors.Add(new Color(color));
                                        }
                                    }
                                    break;
                            }
                        }
                    }
                }

                // Only what the file ACTUALLY has: an empty Set still raised the semantic flag, so a positions-only
                // mesh claimed normals, four UV sets and colors. Tangents were then computed off those flags - over
                // empty arrays.
                rawMesh.SetPoints(rawGeometryData.Positions);
                if (rawGeometryData.Normals.Count > 0) rawMesh.SetNormals(rawGeometryData.Normals);
                if (rawGeometryData.UV0.Count > 0) rawMesh.SetUVs(0, rawGeometryData.UV0);
                if (rawGeometryData.UV1.Count > 0) rawMesh.SetUVs(1, rawGeometryData.UV1);
                if (rawGeometryData.UV2.Count > 0) rawMesh.SetUVs(2, rawGeometryData.UV2);
                if (rawGeometryData.UV3.Count > 0) rawMesh.SetUVs(3, rawGeometryData.UV3);
                if (rawGeometryData.Colors.Count > 0) rawMesh.SetColors(rawGeometryData.Colors);
            }

            return rawMesh;
        }

        //Method to get indices List from Collada versions 1.4.0 and 1.4.1
        internal List<RawIndicesSemanticData> GetRawIndicesCollada(geometry geometry)
        {
            var mesh = geometry.Item as mesh;

            if (mesh != null)
            {
                var rawDataList = new List<RawIndicesSemanticData>();
                InputLocalOffset[] inputs = null;
                String positionId = String.Empty;

                // A <mesh> with no <vertices>, or with an empty input list, is a mesh without positions. NRE before.
                var vertices = mesh.vertices;
                var vertexInput = vertices?.input;
                if (vertexInput == null || vertexInput.Length == 0 || mesh.Items == null)
                {
                    return rawDataList;
                }

                // Positions are the input with the POSITION semantic. The first one used to be taken blindly, and
                // with several inputs (<vertices> may carry NORMAL too) none was, leaving the mapping silently empty.
                var positionInput = System.Array.Find(vertexInput, x => x.semantic == RawPositionSemantic)
                                    ?? vertexInput[0];
                positionId = Source(positionInput.source);

                foreach (var meshItem in mesh.Items)
                {
                    var rawData = new RawIndicesSemanticData();

                    if (meshItem is lines)
                    {
                        var lines = meshItem as lines;
                        String materialId = lines.material;
                        inputs = lines.input;
                        rawData.MaterialId = materialId;
                        rawData.MeshTopology = PrimitiveType.LineList;
                        rawData.RawIndices = new List<int>(COLLADA.ConvertToIntArray(lines.p));
                    }
                    //from version 1.4.0
                    else if (meshItem is polygons polygons)
                    {
                        // Each <p> is ONE polygon, and only it knows how many vertices it has. Every <p> used to be
                        // merged into one list and declared triangles: any quad broke. Now each one's size goes to
                        // vcount and triangulation does its job.
                        var indices = new List<int>();
                        var counts = new List<int>();
                        var stride = System.Math.Max(1, MaxOffset(polygons.input) + 1);

                        foreach (var item in polygons.Items)
                        {
                            // <ph> is a polygon WITH A HOLE. We cannot parse one, and taking just the outer contour
                            // would fill the hole in silence.
                            if (item is not string text)
                            {
                                ReportUnsupported($"{geometry.id}: <ph> (polygon with a hole) skipped");
                                continue;
                            }

                            var before = indices.Count;
                            foreach (var part in text.Split(WhiteSpace, StringSplitOptions.RemoveEmptyEntries))
                            {
                                if (int.TryParse(part, out var index)) indices.Add(index);
                            }

                            counts.Add((indices.Count - before) / stride);
                        }

                        rawData.MaterialId = polygons.material;
                        inputs = polygons.input;
                        rawData.MeshTopology = PrimitiveType.TriangleList;
                        rawData.RawIndices = indices;
                        rawData.VertexType = counts;
                    }
                    //Version 1.4.1
                    else if (meshItem is triangles)
                    {
                        var triangles = meshItem as triangles;
                        String materialId = triangles.material;
                        inputs = triangles.input;
                        rawData.MaterialId = materialId;
                        rawData.MeshTopology = PrimitiveType.TriangleList;
                        rawData.RawIndices = new List<int>(COLLADA.ConvertToIntArray(triangles.p));
                    }
                    //Version 1.4.1
                    else if (meshItem is polylist)
                    {
                        var triangles = meshItem as polylist;
                        String materialId = triangles.material;
                        inputs = triangles.input;
                        rawData.MaterialId = materialId;
                        rawData.MeshTopology = PrimitiveType.TriangleList;
                        rawData.RawIndices = new List<int>(COLLADA.ConvertToIntArray(triangles.p));
                        rawData.VertexType = new List<int>(COLLADA.ConvertToIntArray(triangles.vcount));
                    }
                    else
                    {
                        throw new TopologyNotSupportedException(meshItem.GetType().FullName + "is not supported");
                    }

                    //same for all versions
                    if (inputs != null)
                    {
                        foreach (var input in inputs)
                        {
                            // Even an input we do not read takes a slot in every vertex - see Offset.Observe.
                            rawData.Offset.Observe(input.offset);

                            if (input.semantic == PositionSemantic)
                            {
                                rawData.Offset.Position = input.offset;
                                if (vertices.id == Source(input.source))
                                {
                                    rawData.MapSource(positionId, VertexSemantic.Position);
                                }
                                rawData.Semantic |= VertexSemantic.Position;
                            }
                            else if (input.semantic == NormalSemantic)
                            {
                                rawData.Offset.Normal = input.offset;
                                rawData.MapSource(Source(input.source), VertexSemantic.Normal);
                                rawData.Semantic |= VertexSemantic.Normal;
                            }
                            else if (input.semantic == UVSemantic)
                            {
                                if (input.set == 0)
                                {
                                    rawData.Offset.UV0 = input.offset;
                                    rawData.MapSource(Source(input.source),VertexSemantic.UV0);
                                    rawData.Semantic |= VertexSemantic.UV0;
                                }
                                else if (input.set == 1)
                                {
                                    rawData.Offset.UV1 = input.offset;
                                    rawData.MapSource(Source(input.source),VertexSemantic.UV1);
                                    rawData.Semantic |= VertexSemantic.UV1;
                                }
                                else if (input.set == 2)
                                {
                                    rawData.Offset.UV2 = input.offset;
                                    rawData.MapSource(Source(input.source),VertexSemantic.UV2);
                                    rawData.Semantic |= VertexSemantic.UV2;
                                }
                                else if (input.set == 3)
                                {
                                    rawData.Offset.UV3 = input.offset;
                                    rawData.MapSource(Source(input.source),VertexSemantic.UV3);
                                    rawData.Semantic |= VertexSemantic.UV3;
                                }
                                else
                                {
                                    ReportUnsupported($"{geometry.id}: TEXCOORD set={input.set} skipped - " +
                                                      "a mesh has only four coordinate sets");
                                }
                            }

                            else if (input.semantic == ColorSemantic)
                            {
                                rawData.Offset.Color = input.offset;
                                rawData.MapSource(Source(input.source), VertexSemantic.Color);
                                rawData.Semantic |= VertexSemantic.Color;
                            }
                            else
                            {
                                // TANGENT, TEXBINORMAL and the rest take up a slot in every vertex (Observe above
                                // accounted for that) but we read no data from them. Saying so beats guessing later.
                                ReportUnsupported($"{geometry.id}: input {input.semantic} is not read");
                            }
                        }
                    }
                    rawDataList.Add(rawData);
                }

                return rawDataList;
            }
            return null;
        }

        #endregion


        #region Textures

        public SceneData.Image GetImage(String filePath, image img)
        {
            SceneData.Image images = new SceneData.Image();
            images.ID = img.id;
            images.ImageName = Uri.UnescapeDataString(img.Item.ToString());
            //Where the texture sits on this machine; the artifact keeps only ImageName
            images.FilePath = Path.Combine(Path.GetDirectoryName(filePath), images.ImageName);
            return images;
        }

        #endregion


        #region Controllers and animation

        public SceneData.Controller GetControllerData(controller controller, String filepath)
        {
            skin skin = controller.Item as skin;
            if (skin != null)
            {
                SceneData.Controller animationController = new SceneData.Controller();
                animationController.MeshId = Source(skin.source1);
                animationController.ControllerId = controller.id;
                animationController.Name = controller.name;
                Dictionary<String, ControllerSemantic> controllerMapping = new Dictionary<string, ControllerSemantic>();
                foreach (InputLocalOffset inputLocalOffset in skin.vertex_weights?.input ?? Array.Empty<InputLocalOffset>())
                {
                    if (inputLocalOffset.semantic == ControllerJointSemantic)
                    {
                        controllerMapping[Source(inputLocalOffset.source)] = ControllerSemantic.Joint;
                    }
                    else if (inputLocalOffset.semantic == ControllerWeightSemantic)
                    {
                        controllerMapping[Source(inputLocalOffset.source)] = ControllerSemantic.Weight;
                    }
                }

                foreach (var inputLocal in skin.joints?.input ?? Array.Empty<InputLocal>())
                {
                    if (inputLocal.semantic == ControllerInvBindMatrixSemantic)
                    {
                        controllerMapping[Source(inputLocal.source)] = ControllerSemantic.InverseBindMatrix;
                    }
                }

                // The neighbouring inputs got their null check, these two lines did not - a skin without
                // <vertex_weights> is legal (the mesh is simply bound to nothing) and gave an NRE here.
                if (skin.vertex_weights?.vcount == null || skin.vertex_weights.v == null)
                {
                    ReportUnsupported($"{controller.id}: skin without <vertex_weights> - no bone weights were read");
                    return null;
                }

                List<int> vcountList = new List<int>(COLLADA.ConvertToIntArray(skin.vertex_weights.vcount));
                int[] list = COLLADA.ConvertToIntArray(skin.vertex_weights.v);
                List<int> bonesIndices = new List<int>();
                List<int> weightIndices = new List<int>();
                string[] jointNames = null;
                List<Matrix4x4F> jointsMatrices = new List<Matrix4x4F>();
                float[] weightsValues = null;
                source[] sources = skin.source;
                var bindShape = COLLADA.ConvertToDoubleArray(skin.bind_shape_matrix);
                animationController.BindShapeMatrix = new Matrix4x4F(Array.ConvertAll(bindShape, x => (float)x));
                foreach (source source in sources)
                {
                    // On a source no <input> references, the indexer used to throw KeyNotFound
                    if (!controllerMapping.TryGetValue(source.id, out var semantic))
                    {
                        continue;
                    }

                    if (semantic == ControllerSemantic.Joint)
                    {
                        // In 1.4 bone names legally arrive as <IDREF_array> too - this stayed null then, and the
                        // loop below threw on jointNames.Length.
                        jointNames = (source.Item as Name_array)?.Values;
                        var references = (source.Item as IDREF_array)?.Value;
                        if (jointNames == null && !String.IsNullOrWhiteSpace(references))
                        {
                            jointNames = references.Split(WhiteSpace, StringSplitOptions.RemoveEmptyEntries);
                        }
                    }
                    else if (semantic == ControllerSemantic.InverseBindMatrix)
                    {
                        float_array floatArray = source.Item as float_array;
                        float[] jointArray = null;
                        if (floatArray != null)
                        {
                            jointArray = COLLADA.ConvertToFloatArray(floatArray._Text_);
                        }

                        if (jointArray != null)
                        {
                            List<float> tmpJointsList = new List<float>(COLLADA.ConvertToFloatArray(floatArray._Text_));
                            for (int i = 0; i < tmpJointsList.Count; i += 16)
                            {
                                Matrix4x4F matrix = new Matrix4x4F(tmpJointsList.GetRange(i, 16).ToArray());
                                if (config.MatrixTransposeNeeded)
                                {
                                    matrix = Matrix4x4F.Transpose(matrix);
                                }
                                //AssembleModel changes the coordinate system - meshes, bones and key frames at once
                                jointsMatrices.Add(matrix);
                            }
                        }
                    }

                    else if (semantic == ControllerSemantic.Weight)
                    {
                        float_array array = source.Item as float_array;
                        if (array != null)
                        {
                            weightsValues = COLLADA.ConvertToFloatArray(array._Text_);
                            if (weightsValues == null)
                            {
                                return null;
                            }
                        }
                    }
                }

                if (jointNames == null)
                {
                    ReportUnsupported($"{controller.id}: bone names could not be read - skin skipped");
                    return null;
                }

                for (int i = 0; i < jointNames.Length; i++)
                {
                    // There may be fewer matrices than names: before this check such a file gave IndexOutOfRange,
                    // and a repeated bone name threw on Add.
                    if (i >= jointsMatrices.Count) break;
                    animationController.JointDictionary[jointNames[i]] = jointsMatrices[i];
                }
                animationController.JointNames.AddRange(jointNames);
                animationController.JointMatrices.AddRange(jointsMatrices);

                for (int i = 0; i < list.Length; i++)
                {
                    if (i % 2 == 0)
                    {
                        bonesIndices.Add(list[i]);
                    }
                    else
                    {
                        weightIndices.Add(list[i]);
                    }
                }

                int offset = 0;
                int trimmedVertices = 0;
                var influences = new List<(int Bone, float Weight)>();
                //<v> pairs up bone and weight indices: every first element indexes the bone array, every second
                //the weight array. <vcount> says how many bones influence the vertex currently being walked.
                for (int i = 0; i < vcountList.Count; i++)
                {
                    influences.Clear();
                    for (int j = 0; j < vcountList[i] && offset < bonesIndices.Count && offset < weightIndices.Count; j++)
                    {
                        var weightIndex = weightIndices[offset];
                        var weight = weightsValues != null && weightIndex >= 0 && weightIndex < weightsValues.Length
                            ? weightsValues[weightIndex]
                            : 0f;
                        influences.Add((bonesIndices[offset], weight));
                        offset++;
                    }

                    // A vertex may be bound to more than four bones. Dropping the extras is not enough - the
                    // HEAVIEST ones must be kept and the weights renormalized, or they sum to less than one and
                    // skinning drags that vertex towards the origin.
                    if (influences.Count > 4)
                    {
                        influences.Sort((a, b) => b.Weight.CompareTo(a.Weight));
                        influences.RemoveRange(4, influences.Count - 4);
                        trimmedVertices++;
                    }

                    var total = influences.Sum(x => x.Weight);
                    Vector4F indices = new Vector4F();
                    Vector4F weights = new Vector4F();
                    for (int j = 0; j < influences.Count; j++)
                    {
                        var normalized = total > 0 ? influences[j].Weight / total : 0f;
                        switch (j)
                        {
                            case 0: indices.X = influences[j].Bone; weights.X = normalized; break;
                            case 1: indices.Y = influences[j].Bone; weights.Y = normalized; break;
                            case 2: indices.Z = influences[j].Bone; weights.Z = normalized; break;
                            case 3: indices.W = influences[j].Bone; weights.W = normalized; break;
                        }
                    }
                    animationController.BoneIndices.Add(indices);
                    animationController.BoneWeights.Add(weights);
                }

                if (trimmedVertices > 0)
                {
                    ReportUnsupported($"{controller.id}: {trimmedVertices} vertices had more than 4 bones - the four " +
                                      "heaviest were kept and the weights renormalized");
                }
                return animationController;
            }
            return null;
        }

        //library_animations is parsed in ColladaConversionExecutor.Animation.cs

        #endregion


        #region Visual scenes

        //Builds an object's transform from a visual-scene node, whichever form the node uses
        internal MatrixParams GetObjectMatrix(node node)
        {
            bool matrixTransposeNeeded = config.MatrixTransposeNeeded;
            bool singleMatrixPresent = false;
            MatrixParams parameters = MatrixParams.Default;
            Matrix4x4F result = Matrix4x4F.Identity;
            if (node.Items == null)
            {
                return parameters;
            }

            foreach (Matrix4x4F meshMatrix in node.Items.OfType<matrix>().Select(matr => new Matrix4x4F(Array.ConvertAll(matr.Values, x => (float)x))))
            {
                if (matrixTransposeNeeded)
                {
                    meshMatrix.Transpose();
                }
                result = meshMatrix;
                singleMatrixPresent = true;
                break;
            }
            if (!singleMatrixPresent)
            {
                Vector3F translation = Vector3F.Zero;
                Vector3F scale = Vector3F.One;
                float rotationX = 0;
                float rotationY = 0;
                float rotationZ = 0;

                foreach (var item in node.Items)
                {
                    if (item is TargetableFloat3)
                    {
                        TargetableFloat3 target = item as TargetableFloat3;
                        var values = COLLADA.ConvertToFloatArray(target._Text_);
                        switch (target.sid)
                        {
                            case "scale":
                                scale = new Vector3F(values);
                                break;
                            default:
                                translation = new Vector3F(values);
                                break;
                        }
                    }
                    else if (item is rotate)
                    {
                        rotate rotate = item as rotate;
                        switch (rotate.sid)
                        {
                            case "rotationX":
                            case "rotateX":
                                rotationX = MathHelper.DegreesToRadians((float)rotate.Values[rotate.Values.Length - 1]);
                                break;
                            case "rotationY":
                            case "rotateY":
                                rotationY = MathHelper.DegreesToRadians((float)rotate.Values[rotate.Values.Length - 1]);
                                break;
                            case "rotationZ":
                            case "rotateZ":
                                rotationZ = MathHelper.DegreesToRadians((float)rotate.Values[rotate.Values.Length - 1]);
                                break;
                        }
                    }
                }
                parameters.Scale = scale;
                parameters.Translation = translation;
                parameters.Rotation = QuaternionF.RotationYawPitchRoll(rotationY, rotationX, rotationZ);

                return parameters;
                //result = Matrix4x4F.Scaling(scale) * Matrix4x4F.RotationX(rotationX) * Matrix4x4F.RotationX(rotationY) * Matrix4x4F.RotationX(rotationZ) *
                //                 Matrix4x4F.Translation(translation);

            }
            //AssembleModel changes the coordinate system - meshes, nodes, bones and key frames at once. Here it was
            //changed for Z_UP only, and only in the single-matrix branch: a component-wise pose was never converted.
            result.Decompose(out parameters.Scale, out parameters.Rotation, out parameters.Translation);
            return parameters;
        }

        //Get hierarchy from Visual scenes node
        public void GetMeshStructure(SceneData dataContainer, visual_scene visualScene, List<geometry> geometries,
           List<controller> controllers)
        {
            if (visualScene == null)
            {
                return;
            }

            Dictionary<node, SceneData.Model> nodeToMesh = new Dictionary<node, SceneData.Model>();
            foreach (var node in visualScene.node)
            {
                if (node == null)
                {
                    continue;
                }

                Dictionary<node, SceneData.Joint> nodeToJoint = new Dictionary<node, SceneData.Joint>();

                SceneData.Joint joint = null;
                SceneData.Model mesh = null;

                var queue = new Queue<node>();
                queue.Enqueue(node);
                string controllerName = string.Empty;
                while (queue.Count > 0)
                {
                    var currentNode = queue.Dequeue();
                    GetLightsAndCameraTranformation(dataContainer, currentNode);

                    mesh = GetMeshStructure(dataContainer, currentNode, nodeToMesh, geometries, controllers);

                    if (config.GetJoints)
                    {
                        joint = GetJoint(currentNode, nodeToJoint);
                        if (joint != null && joint.ParentJoint == null)
                        {
                            List<SceneData.Joint> joints;
                            if (dataContainer.Skeletons.TryGetValue(controllerName, out joints))
                            {
                                joints.Add(joint);
                            }
                        }
                    }
                    if (currentNode.node1 != null)
                    {
                        foreach (var node1 in currentNode.node1)
                        {
                            //If child node is joint and current node is NOT joint, it means that current joint contains controller name,
                            //which is corresponding to the name of controller in library_controllers
                            if (node1.type == NodeType.JOINT
                               && currentNode.type == NodeType.NODE
                               && string.IsNullOrEmpty(controllerName))
                            {
                                controllerName = currentNode.id;
                                if (!dataContainer.Skeletons.ContainsKey(controllerName))
                                {
                                    dataContainer.Skeletons.Add(controllerName, new List<SceneData.Joint>());
                                }
                            }

                            queue.Enqueue(node1);
                            if (joint != null)
                            {
                                nodeToJoint.Add(node1, joint);
                            }
                            if (mesh != null)
                            {
                                nodeToMesh.Add(node1, mesh);
                            }
                        }
                    }
                }
            }

            RemoveDeadEndMeshes(dataContainer);
        }

        private void RemoveDeadEndMeshes(SceneData model)
        {
            List<SceneData.Model> meshesToRemove = new List<SceneData.Model>();
            Stack<SceneData.Model> stack = new Stack<SceneData.Model>();
            stack.Push(model.Models);
            while (stack.Count > 0)
            {
                var current = stack.Pop();

                // The root is not a dead-end mesh but the scene's container. Without Parent != null, a scene of
                // joints alone (or of lights and cameras) took away the ROOT, RemoveMesh nulled Models, and
                // assembly threw.
                if (current.Dependencies.Count == 0 && String.IsNullOrEmpty(current.ID) && current.Parent != null)
                {
                    meshesToRemove.Add(current);
                }

                foreach (var mesh in current.Dependencies)
                {
                    stack.Push(mesh);
                }
            }

            foreach (var mesh in meshesToRemove)
            {
                var incorrectMesh = mesh;
                while (String.IsNullOrEmpty(incorrectMesh.ID) && incorrectMesh.Parent != null)
                {
                    var temp = incorrectMesh.Parent;
                    if (temp.Meshes.Count == 0 && temp.Parent != null)
                    {
                        incorrectMesh = temp;
                    }
                    else
                    {
                        break;
                    }
                }
                model.RemoveMesh(incorrectMesh);
            }
        }

        private SceneData.Model GetMeshStructure(SceneData model, node rootNode, Dictionary<node, SceneData.Model> nodeToMesh, List<geometry> geometries, List<controller> controllers)
        {
            if (rootNode.type != NodeType.JOINT && rootNode.instance_camera == null && rootNode.instance_light == null)
            {
                var nodeName = !String.IsNullOrEmpty(rootNode.name) ? rootNode.name : rootNode.id;
                string geometryId = String.Empty;
                if (rootNode.instance_geometry != null)
                {
                    geometryId = Source(rootNode.instance_geometry[0].url);
                }
                else if (rootNode.instance_controller != null)
                {
                    var controllerId = Source(rootNode.instance_controller[0].url);
                    foreach (var controller in controllers)
                    {
                        if (controllerId == controller.id)
                        {
                            geometryId = Source(((skin)controller.Item).source1);
                            break;
                        }
                    }
                }

                bool meshFound = false;
                foreach (var geometry in geometries)
                {
                    if (geometry.id == geometryId)
                    {
                        meshFound = true;
                        break;
                    }
                }

                if (meshFound || rootNode.node1 != null)
                {
                    SceneData.Model parentMesh;
                    if (!nodeToMesh.TryGetValue(rootNode, out parentMesh))
                    {
                        parentMesh = model.Models;
                    }
                    var meshData = model.CreateMesh(parentMesh, geometryId, nodeName);

                    if (config.GetMeshMatrices)
                    {
                        var matrixParams = GetObjectMatrix(rootNode);
                        meshData.Scale = matrixParams.Scale;
                        meshData.Rotation = matrixParams.Rotation;
                        meshData.Position = matrixParams.Translation;
                    }
                    return meshData;
                }
            }
            return null;
        }

        public void GetLightsAndCameraTranformation(SceneData dataContainer, node rootNode)
        {
            if (rootNode.type == NodeType.JOINT)
            {
                return;
            }

            InstanceWithExtra[] nodeIds = rootNode.instance_light;
            if (nodeIds != null && config.LightsEnabled)
            {
                string lightId = Source(nodeIds[0].url);
                foreach (var light in dataContainer.LightData)
                {
                    if (light.Value.ID == lightId)
                    {
                        var matrix = GetObjectMatrix(rootNode);
                        light.Value.Position = matrix.Translation;
                        light.Value.Scale = matrix.Scale;
                        light.Value.Rotation = matrix.Rotation;
                        break;
                    }
                }
            }

            nodeIds = rootNode.instance_camera;
            if (nodeIds != null && config.CamerasEnabled)
            {
                string cameraId = Source(nodeIds[0].url);
                foreach (var camera in dataContainer.CameraData)
                {
                    if (camera.Value.ID == cameraId)
                    {
                        var matrix = GetObjectMatrix(rootNode);
                        camera.Value.Translation = matrix.Translation;
                        camera.Value.Rotation = matrix.Rotation;
                        break;
                    }
                }
            }

        }

        private SceneData.Joint GetJoint(node rootNode, Dictionary<node, SceneData.Joint> nodeToJoint)
        {
            if (rootNode.type != NodeType.JOINT)
            {
                return null;
            }

            SceneData.Joint rootJoint;
            nodeToJoint.TryGetValue(rootNode, out rootJoint);
            var joint = new SceneData.Joint
            {
                JointSid = rootNode.sid,
                JointName = rootNode.name,
                ParentJoint = rootJoint,
            };

            rootJoint?.Children.Add(joint);

            var matr = rootNode.Items[0] as matrix;
            if (matr != null)
            {
                var matrix = new Matrix4x4F(Array.ConvertAll(matr.Values, x => (float)x));
                if (config.MatrixTransposeNeeded)
                {
                    matrix = Matrix4x4F.Transpose(matrix);
                }
                //AssembleModel changes the coordinate system - meshes, bones and key frames at once
                joint.LocalMatrix = matrix;
            }

            return joint;
        }


        //Reads the material bindings out of the visual scenes
        public void ResolveMaterialsBinding(SceneData sceneData, visual_scene visualScene)
        {
            if (visualScene != null)
            {
                foreach (var node in visualScene.node)
                {
                    FindMaterialsBinding(sceneData, node);
                }
            }
        }

        private void FindMaterialsBinding(SceneData sceneData, node node)
        {
            if (node != null && node.type != NodeType.JOINT)
            {
                Stack<node> stack = new Stack<node>();
                stack.Push(node);
                while (stack.Count > 0)
                {
                    var root = stack.Pop();
                    instance_geometry[] nodeId = root.instance_geometry;
                    if (nodeId != null)
                    {
                        string meshId = Source(nodeId[0].url);
                        var mesh = sceneData.GetModelByID(meshId);
                        if (mesh != null)
                        {
                            int i = 0;
                            if (nodeId[0].bind_material != null)
                            {
                                foreach (var materialInstance in nodeId[0].bind_material.technique_common)
                                {
                                    mesh.Meshes[i].MaterialID = Source(materialInstance.target);
                                    i++;
                                }
                            }
                        }
                    }
                    if (root.node1 != null)
                    {
                        foreach (var node1 in root.node1)
                        {
                            stack.Push(node1);
                        }
                    }
                }
            }
        }

        #endregion


        #region Materials

        //Maps the format's surface-type enum onto ours, so the right kind of texture gets created later
        private TextureDimension ResolveTextureDimension(fx_surface_type_enum surfaceType)
        {
            switch (surfaceType)
            {
                case fx_surface_type_enum.Item1D:
                    return TextureDimension.Texture1D;
                case fx_surface_type_enum.Item2D:
                    return TextureDimension.Texture2D;
                case fx_surface_type_enum.Item3D:
                    return TextureDimension.Texture3D;
                case fx_surface_type_enum.CUBE:
                    return TextureDimension.Texture3D;
                case fx_surface_type_enum.DEPTH:
                    return TextureDimension.DepthBuffer;
                case fx_surface_type_enum.RECT:
                    return TextureDimension.Rectangle;
                case fx_surface_type_enum.UNTYPED:
                    return TextureDimension.None;
            }
            return TextureDimension.None;
        }

        public SceneData.Material GetMaterial(effect effect)
        {
            SceneData.Material materialData = new SceneData.Material();

            foreach (var profile in effect.Items)
            {
                if (profile.Items != null)
                {
                    foreach (var item in profile.Items)
                    {
                        if (item is common_newparam_type)
                        {
                            var param = item as common_newparam_type;
                            if (param.ItemElementName == ItemChoiceType.surface)
                            {
                                var initFrom = param.Item as fx_surface_common;
                                //materialData.TextureDimension = ResolveTextureDimension(initFrom.type);
                                foreach (fx_surface_init_from_common init in initFrom.init_from)
                                {
                                    materialData.DiffuseMap = init.Value;
                                }
                            }
                        }
                    }
                }
                if (profile.technique.Item is effectFx_profile_abstractProfile_COMMONTechniquePhong)
                {
                    var concreteItem =
                       profile.technique.Item as effectFx_profile_abstractProfile_COMMONTechniquePhong;
                    if (!concreteItem.Equals(null))
                    {
                        if (concreteItem.emission != null)
                        {
                            var color = concreteItem.emission.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Emission =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.ambient != null)
                        {
                            var color =
                               concreteItem.ambient.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.AmbientColor =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.diffuse != null)
                        {
                            if (concreteItem.diffuse.Item is common_color_or_texture_typeColor)
                            {
                                var item = concreteItem.diffuse.Item as common_color_or_texture_typeColor;
                                if (item != null)
                                {
                                    materialData.DiffuseColor =
                                       new Vector4F(Array.ConvertAll(item.Values, x => (float)x));
                                }
                            }
                        }
                        if (concreteItem.specular != null)
                        {
                            var color =
                               concreteItem.specular.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.SpecularColor =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflective != null)
                        {
                            var color =
                               concreteItem.reflective.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Reflective =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.transparent != null)
                        {
                            var color =
                               concreteItem.transparent.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Transparent =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflectivity != null)
                        {
                            var value =
                               concreteItem.reflectivity.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Reflectivity = (Single)value.Value;
                            }
                        }
                        if (concreteItem.shininess != null)
                        {
                            var value =
                               concreteItem.shininess.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Shininess = (Single)value.Value;
                            }
                        }
                        if (concreteItem.transparency != null)
                        {
                            var value =
                               concreteItem.transparency.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Transparency = (Single)value.Value;
                            }
                        }
                        if (concreteItem.index_of_refraction != null)
                        {
                            var value =
                               concreteItem.index_of_refraction.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.RefractionIndex = (Single)value.Value;
                            }
                        }
                    }
                }

                else if (profile.technique.Item is effectFx_profile_abstractProfile_COMMONTechniqueBlinn)
                {
                    var concreteItem =
                       profile.technique.Item as effectFx_profile_abstractProfile_COMMONTechniqueBlinn;

                    if (!concreteItem.Equals(null))
                    {
                        if (concreteItem.emission != null)
                        {
                            var color = concreteItem.emission.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Emission =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.ambient != null)
                        {
                            var color =
                               concreteItem.ambient.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.AmbientColor =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.diffuse != null)
                        {
                            if (concreteItem.diffuse.Item is common_color_or_texture_typeColor)
                            {
                                var item = concreteItem.diffuse.Item as common_color_or_texture_typeColor;
                                if (item != null)
                                {
                                    materialData.DiffuseColor =
                                       new Vector4F(Array.ConvertAll(item.Values, x => (float)x));
                                }
                            }
                        }
                        if (concreteItem.specular != null)
                        {
                            var color =
                               concreteItem.specular.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.SpecularColor =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflective != null)
                        {
                            var color =
                               concreteItem.reflective.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Reflective =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.transparent != null)
                        {
                            var color =
                               concreteItem.transparent.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Transparent =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflectivity != null)
                        {
                            var value =
                               concreteItem.reflectivity.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Reflectivity = (Single)value.Value;
                            }
                        }
                        if (concreteItem.shininess != null)
                        {
                            var value =
                               concreteItem.shininess.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Shininess = (Single)value.Value;
                            }
                        }
                        if (concreteItem.transparency != null)
                        {
                            var value =
                               concreteItem.transparency.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Transparency = (Single)value.Value;
                            }
                        }
                        if (concreteItem.index_of_refraction != null)
                        {
                            var value =
                               concreteItem.index_of_refraction.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.RefractionIndex = (Single)value.Value;
                            }
                        }
                    }
                }

                else if (profile.technique.Item is effectFx_profile_abstractProfile_COMMONTechniqueLambert)
                {
                    var concreteItem =
                       profile.technique.Item as effectFx_profile_abstractProfile_COMMONTechniqueLambert;
                    if (!concreteItem.Equals(null))
                    {
                        if (concreteItem.emission != null)
                        {
                            var color = concreteItem.emission.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Emission =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.ambient != null)
                        {
                            var color =
                               concreteItem.ambient.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.AmbientColor =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.diffuse != null)
                        {
                            if (concreteItem.diffuse.Item is common_color_or_texture_typeColor)
                            {
                                var item = concreteItem.diffuse.Item as common_color_or_texture_typeColor;
                                if (item != null)
                                {
                                    materialData.DiffuseColor =
                                       new Vector4F(Array.ConvertAll(item.Values, x => (float)x));
                                }
                            }
                        }
                        if (concreteItem.reflective != null)
                        {
                            var color =
                               concreteItem.reflective.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Reflective =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.transparent != null)
                        {
                            var color =
                               concreteItem.transparent.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Transparent =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflectivity != null)
                        {
                            var value =
                               concreteItem.reflectivity.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Reflectivity = (Single)value.Value;
                            }
                        }
                        if (concreteItem.transparency != null)
                        {
                            var value =
                               concreteItem.transparency.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Transparency = (Single)value.Value;
                            }
                        }
                        if (concreteItem.index_of_refraction != null)
                        {
                            var value =
                               concreteItem.index_of_refraction.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.RefractionIndex = (Single)value.Value;
                            }
                        }
                    }
                }

                else if (profile.technique.Item is effectFx_profile_abstractProfile_COMMONTechniqueConstant)
                {
                    var concreteItem =
                       profile.technique.Item as effectFx_profile_abstractProfile_COMMONTechniqueConstant;

                    if (!concreteItem.Equals(null))
                    {
                        if (concreteItem.emission != null)
                        {
                            var color = concreteItem.emission.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Emission =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflective != null)
                        {
                            var color =
                               concreteItem.reflective.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Reflective =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.transparent != null)
                        {
                            var color =
                               concreteItem.transparent.Item as common_color_or_texture_typeColor;
                            if (color != null)
                            {
                                materialData.Transparent =
                                   new Vector4F(Array.ConvertAll(color.Values, x => (float)x));
                            }
                        }
                        if (concreteItem.reflectivity != null)
                        {
                            var value =
                               concreteItem.reflectivity.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Reflectivity = (Single)value.Value;
                            }
                        }
                        if (concreteItem.transparency != null)
                        {
                            var value =
                               concreteItem.transparency.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.Transparency = (Single)value.Value;
                            }
                        }
                        if (concreteItem.index_of_refraction != null)
                        {
                            var value =
                               concreteItem.index_of_refraction.Item as common_float_or_param_typeFloat;
                            if (value != null)
                            {
                                materialData.RefractionIndex = (Single)value.Value;
                            }
                        }
                    }
                }
            }
            return materialData;
        }


        #endregion


        #region Lights

        public SceneData.Light GetLight(light light)
        {
            SceneData.Light lightData = new SceneData.Light();
            lightData.ID = light.id;
            if (light.technique_common.Item is lightTechnique_commonAmbient)
            {
                var lightType = light.technique_common.Item as lightTechnique_commonAmbient;
                lightData.Color = new Vector3F(Array.ConvertAll(lightType.color.Values, x => (float)x));
                lightData.LightType = LightType.Ambient;
            }
            else if (light.technique_common.Item is lightTechnique_commonDirectional)
            {
                var lightType = light.technique_common.Item as lightTechnique_commonDirectional;
                lightData.Color = new Vector3F(Array.ConvertAll(lightType.color.Values, x => (float)x));
                lightData.LightType = LightType.Directional;
            }
            else if (light.technique_common.Item is lightTechnique_commonPoint)
            {
                var lightType = light.technique_common.Item as lightTechnique_commonPoint;
                lightData.Color = new Vector3F(Array.ConvertAll(lightType.color.Values, x => (float)x));
                lightData.ConstantAttenuation = (float)lightType.constant_attenuation.Value;
                lightData.LinearAttenuation = (float)lightType.linear_attenuation.Value;
                lightData.QuadraticAttenuation = (float)lightType.quadratic_attenuation.Value;
                lightData.LightType = LightType.Point;
            }
            else if (light.technique_common.Item is lightTechnique_commonSpot)
            {
                var lightType = light.technique_common.Item as lightTechnique_commonSpot;
                lightData.Color = new Vector3F(Array.ConvertAll(lightType.color.Values, x => (float)x));
                lightData.ConstantAttenuation = (float)lightType.constant_attenuation.Value;
                lightData.LinearAttenuation = (float)lightType.linear_attenuation.Value;
                lightData.QuadraticAttenuation = (float)lightType.quadratic_attenuation.Value;
                lightData.FalloffAngle = (float)lightType.falloff_angle.Value;
                lightData.FalloffExponent = (float)lightType.falloff_exponent.Value;
                lightData.LightType = LightType.Directional;
            }
            return lightData;
        }

        #endregion


        #region Cameras

        public SceneData.Camera GetCamera(camera camera)
        {
            SceneData.Camera cameraData = new SceneData.Camera();
            cameraData.ID = camera.id;
            var cameraItem = camera.optics.technique_common.Item;
            if (cameraItem is cameraOpticsTechnique_commonPerspective)
            {
                var perspective = cameraItem as cameraOpticsTechnique_commonPerspective;
                cameraData.ZNear = (Single)perspective.znear.Value;
                cameraData.ZFar = (Single)perspective.zfar.Value;
                cameraData.ProjectionType = CameraProjectionType.Pespective;
                for (int i = 0; i < perspective.Items.Length; i++)
                {
                    if (perspective.ItemsElementName[i] == ItemsChoiceType1.xfov)
                    {
                        cameraData.FovType = FovType.XFov;
                        cameraData.Fov = (float)perspective.Items[i].Value;
                    }
                    else if (perspective.ItemsElementName[i] == ItemsChoiceType1.yfov)
                    {
                        cameraData.FovType = FovType.YFov;
                        cameraData.Fov = (float)perspective.Items[i].Value;
                    }
                    else if (perspective.ItemsElementName[i] == ItemsChoiceType1.aspect_ratio)
                    {
                        cameraData.AspectRatio = (float)perspective.Items[i].Value;
                    }
                }
            }
            return cameraData;
        }

        #endregion

    }
}
