using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Adamantium.Engine.Compiler.Converter.AutoGenerated;
using Adamantium.Graphics.Core.Models;
using Adamantium.Mathematics;

namespace Adamantium.Engine.Compiler.Models.ConversionUtils
{
    /// <summary>
    /// Parses library_animations. Kept apart from the rest of the executor because it is shaped differently: a
    /// COLLADA channel does not target "the joint's animation" but ONE PROPERTY of a node, and one joint often has
    /// many channels - spread across separate &lt;animation&gt; elements and sampled at different times. So every
    /// channel in the document is collected first, then grouped per joint, and only then folded into key frames.
    /// </summary>
    internal partial class ColladaConversionExecutor
    {
        private const String TransformMember = "transform";

        //What of the node the channel drives
        private enum ChannelTarget
        {
            Unknown,
            Matrix,
            Translation,
            Scale,
            RotationX,
            RotationY,
            RotationZ
        }

        private sealed class AnimationChannel
        {
            public String JointId;
            public ChannelTarget Target;
            //Which coordinate the channel touches: 0/1/2 for .X/.Y/.Z, -1 for the whole value
            public int Component = -1;
            public double[] Times;
            public float[] Values;
            public int Stride;
            public InterpolationType[] Interpolations;

            public int FrameCount => Times == null || Stride <= 0 ? 0 : Math.Min(Times.Length, Values.Length / Stride);
        }

        /// <summary>Folds the whole animation library into key frames per joint. `nodes` are the visual-scene nodes
        /// by id and sid: a channel states ONLY what changes, the rest comes from the node's own rest pose.</summary>
        public List<SceneData.FrameCollection> GetAnimations(List<animation> animations, Dictionary<String, node> nodes)
        {
            var samplers = new Dictionary<String, sampler>();
            var sources = new Dictionary<String, source>();
            var channels = new List<channel>();

            // Nested <animation> is how Blender normally exports an action. The branch for it used to be commented
            // out, so such a library imported as zero animations, silently.
            foreach (var animation in animations)
            {
                Collect(animation, samplers, sources, channels);
            }

            var collected = new List<AnimationChannel>();
            foreach (var channel in channels)
            {
                var parsed = ReadChannel(channel, samplers, sources);
                if (parsed != null) collected.Add(parsed);
            }

            var result = new List<SceneData.FrameCollection>();
            foreach (var group in collected.GroupBy(x => x.JointId, StringComparer.Ordinal))
            {
                var frames = Compose(group.Key, group.ToList(), nodes);
                if (frames.Count > 0) result.Add(frames);
            }
            return result;
        }

        private static void Collect(animation animation, Dictionary<String, sampler> samplers,
            Dictionary<String, source> sources, List<channel> channels)
        {
            if (animation?.Items == null) return;

            foreach (var item in animation.Items)
            {
                switch (item)
                {
                    // Indexed across the whole document rather than the current element: a sampler may legally
                    // reference a source in a parent, and nothing fixes the order of children inside <animation>.
                    case source source when !String.IsNullOrEmpty(source.id):
                        sources[source.id] = source;
                        break;
                    case sampler sampler when !String.IsNullOrEmpty(sampler.id):
                        samplers[sampler.id] = sampler;
                        break;
                    case channel channel:
                        channels.Add(channel);
                        break;
                    case animation nested:
                        Collect(nested, samplers, sources, channels);
                        break;
                }
            }
        }

        private AnimationChannel ReadChannel(channel channel, Dictionary<String, sampler> samplers,
            Dictionary<String, source> sources)
        {
            var target = channel?.target;
            if (String.IsNullOrEmpty(target)) return null;

            // Target reads "joint/member". The slash may be absent - that is legal, and used to give Substring(0, -1).
            var slash = target.IndexOf('/');
            var jointId = slash < 0 ? target : target.Substring(0, slash);
            var member = slash < 0 ? TransformMember : target.Substring(slash + 1);
            if (String.IsNullOrEmpty(jointId)) return null;

            if (!samplers.TryGetValue(Source(channel.source), out var sampler) || sampler.input == null) return null;

            source input = null, output = null, interpolation = null;
            foreach (var link in sampler.input)
            {
                if (!sources.TryGetValue(Source(link.source), out var source)) continue;

                if (link.semantic == AnimationInputSemantic) input = source;
                else if (link.semantic == AnimationOutputSemantic) output = source;
                else if (link.semantic == AnimationInterpolationSemantic) interpolation = source;
            }

            var times = (input?.Item as float_array)?.Values;
            var values = (output?.Item as float_array)?.Values;
            if (times == null || values == null || times.Length == 0) return null;

            var parsed = new AnimationChannel
            {
                JointId = jointId,
                Times = times,
                Values = Array.ConvertAll(values, x => (float)x),
                Stride = Stride(output, values.Length, times.Length),
                Interpolations = ReadInterpolations(interpolation, times.Length)
            };
            ResolveTarget(member, parsed);
            return parsed.Target == ChannelTarget.Unknown ? null : parsed;
        }

        //How many numbers make up one frame. The accessor is the authority, but it may be missing
        private static int Stride(source output, int valueCount, int timeCount)
        {
            var stride = (int)(output?.technique_common?.accessor?.stride ?? 0);
            if (stride > 0) return stride;
            return timeCount > 0 ? Math.Max(1, valueCount / timeCount) : 1;
        }

        private static InterpolationType[] ReadInterpolations(source source, int count)
        {
            var names = (source?.Item as Name_array)?.Values;
            var result = new InterpolationType[count];
            for (var i = 0; i < count; i++)
            {
                // An unknown curve name is not worth losing the animation over
                result[i] = names != null && i < names.Length
                            && Enum.TryParse<InterpolationType>(names[i], true, out var parsed)
                    ? parsed
                    : InterpolationType.Linear;
            }
            return result;
        }

        /// <summary>Reads the member name: "transform", "location.X", "rotationZ.ANGLE", "scale". The rotation axis
        /// comes from the sid by the same convention <see cref="GetObjectMatrix"/> uses - otherwise the static pose
        /// and the animation would follow different rules.</summary>
        private static void ResolveTarget(String member, AnimationChannel channel)
        {
            var dot = member.IndexOf('.');
            var name = dot < 0 ? member : member.Substring(0, dot);
            var component = dot < 0 ? null : member.Substring(dot + 1);

            // "transform(3)(0)" addresses a single matrix cell; such a channel is not folded in
            var bracket = name.IndexOf('(');
            if (bracket >= 0) return;

            switch (name)
            {
                case TransformMember when channel.Stride == 16:
                    channel.Target = ChannelTarget.Matrix;
                    return;
                case "location":
                case "translate":
                case "translation":
                    channel.Target = ChannelTarget.Translation;
                    break;
                case "scale":
                    channel.Target = ChannelTarget.Scale;
                    break;
                case "rotationX":
                case "rotateX":
                    channel.Target = ChannelTarget.RotationX;
                    break;
                case "rotationY":
                case "rotateY":
                    channel.Target = ChannelTarget.RotationY;
                    break;
                case "rotationZ":
                case "rotateZ":
                    channel.Target = ChannelTarget.RotationZ;
                    break;
                default:
                    return;
            }

            if (String.IsNullOrEmpty(component)) return;

            switch (component.ToUpperInvariant())
            {
                case "X": channel.Component = 0; break;
                case "Y": channel.Component = 1; break;
                case "Z": channel.Component = 2; break;
                // ANGLE is the last of the four numbers on <rotate>, but a channel carries it alone
                case "ANGLE": channel.Component = -1; break;
                default: channel.Target = ChannelTarget.Unknown; break;
            }
        }

        private SceneData.FrameCollection Compose(String jointId, List<AnimationChannel> channels,
            Dictionary<String, node> nodes)
        {
            var frames = new SceneData.FrameCollection { JointId = jointId };

            var matrixChannel = channels.FirstOrDefault(x => x.Target == ChannelTarget.Matrix && x.FrameCount > 0);
            if (matrixChannel != null)
            {
                ComposeFromMatrices(matrixChannel, frames);
                return frames;
            }

            // A channel states only what changes. Everything else is the node's rest pose - without it a joint that
            // merely rotates would arrive at the origin.
            node node = null;
            nodes?.TryGetValue(jointId, out node);
            var rest = RestPose(node);

            var times = UnionOfTimes(channels);
            foreach (var time in times)
            {
                var translation = rest.Translation;
                var scale = rest.Scale;
                var angles = rest.Angles;

                foreach (var channel in channels)
                {
                    Apply(channel, time, ref translation, ref scale, ref angles);
                }

                //AssembleModel changes the coordinate system - meshes, bones and key frames in one go
                frames.Add(new SceneData.KeyFrame
                {
                    TimeStamp = time,
                    Position = translation,
                    Scale = scale,
                    Rotation = QuaternionF.RotationYawPitchRoll(angles.Y, angles.X, angles.Z),
                    Interpolation = InterpolationAt(channels, time)
                });
            }
            return frames;
        }

        private void ComposeFromMatrices(AnimationChannel channel, SceneData.FrameCollection frames)
        {
            for (var i = 0; i < channel.FrameCount; i++)
            {
                var raw = new float[16];
                Array.Copy(channel.Values, i * 16, raw, 0, 16);
                var matrix = new Matrix4x4F(raw);
                if (config.MatrixTransposeNeeded)
                {
                    matrix = Matrix4x4F.Transpose(matrix);
                }
                //AssembleModel changes the coordinate system - meshes, bones and key frames in one go
                matrix.Decompose(out var scale, out var rotation, out var position);

                frames.Add(new SceneData.KeyFrame
                {
                    TimeStamp = channel.Times[i],
                    Position = position,
                    Scale = scale,
                    Rotation = rotation,
                    Interpolation = channel.Interpolations[i]
                });
            }
        }

        /// <summary>The node's rest pose component by component: translation, scale and three angles. Read straight
        /// off &lt;translate&gt;/&lt;scale&gt;/&lt;rotate&gt; by the same conventions
        /// <see cref="GetObjectMatrix"/> uses - a round trip through a quaternion would not return the angles
        /// exactly.</summary>
        private static (Vector3F Translation, Vector3F Scale, Vector3F Angles) RestPose(node node)
        {
            var translation = Vector3F.Zero;
            var scale = Vector3F.One;
            var angles = Vector3F.Zero;
            if (node?.Items == null) return (translation, scale, angles);

            foreach (var item in node.Items)
            {
                if (item is matrix single)
                {
                    // The node is given as a matrix: the angles cannot be recovered honestly, translation and scale can
                    var composed = new Matrix4x4F(Array.ConvertAll(single.Values, x => (float)x));
                    composed.Decompose(out scale, out _, out translation);
                }
                else if (item is TargetableFloat3 float3)
                {
                    var values = COLLADA.ConvertToFloatArray(float3._Text_);
                    if (values == null || values.Length < 3) continue;

                    if (float3.sid == "scale") scale = new Vector3F(values);
                    else translation = new Vector3F(values);
                }
                else if (item is rotate rotate && rotate.Values != null && rotate.Values.Length > 0)
                {
                    var angle = MathHelper.DegreesToRadians((float)rotate.Values[rotate.Values.Length - 1]);
                    switch (rotate.sid)
                    {
                        case "rotationX":
                        case "rotateX": angles.X = angle; break;
                        case "rotationY":
                        case "rotateY": angles.Y = angle; break;
                        case "rotationZ":
                        case "rotateZ": angles.Z = angle; break;
                    }
                }
            }
            return (translation, scale, angles);
        }

        /// <summary>The union of every channel's time stamps for one joint: rotation and translation are often
        /// sampled differently, and taking one of the two would drop the other's keys.</summary>
        private static List<double> UnionOfTimes(List<AnimationChannel> channels)
        {
            var times = new List<double>();
            foreach (var channel in channels)
            {
                for (var i = 0; i < channel.FrameCount; i++) times.Add(channel.Times[i]);
            }
            times.Sort();

            var unique = new List<double>();
            foreach (var time in times)
            {
                if (unique.Count == 0 || time - unique[unique.Count - 1] > 1e-6) unique.Add(time);
            }
            return unique;
        }

        private static void Apply(AnimationChannel channel, double time, ref Vector3F translation,
            ref Vector3F scale, ref Vector3F angles)
        {
            var sampled = Sample(channel, time);
            if (sampled == null) return;

            switch (channel.Target)
            {
                case ChannelTarget.Translation:
                    Write(ref translation, channel.Component, sampled);
                    break;
                case ChannelTarget.Scale:
                    Write(ref scale, channel.Component, sampled);
                    break;
                case ChannelTarget.RotationX:
                    angles.X = MathHelper.DegreesToRadians(sampled[sampled.Length - 1]);
                    break;
                case ChannelTarget.RotationY:
                    angles.Y = MathHelper.DegreesToRadians(sampled[sampled.Length - 1]);
                    break;
                case ChannelTarget.RotationZ:
                    angles.Z = MathHelper.DegreesToRadians(sampled[sampled.Length - 1]);
                    break;
            }
        }

        private static void Write(ref Vector3F target, int component, float[] values)
        {
            if (component >= 0)
            {
                if (component == 0) target.X = values[0];
                else if (component == 1) target.Y = values[0];
                else target.Z = values[0];
                return;
            }

            if (values.Length >= 3) target = new Vector3F(values[0], values[1], values[2]);
        }

        //The channel's value at any moment: linear between its own keys, the end key beyond them
        private static float[] Sample(AnimationChannel channel, double time)
        {
            var count = channel.FrameCount;
            if (count == 0) return null;

            if (time <= channel.Times[0]) return Frame(channel, 0);
            if (time >= channel.Times[count - 1]) return Frame(channel, count - 1);

            var next = 1;
            while (next < count && channel.Times[next] < time) next++;
            if (next >= count) return Frame(channel, count - 1);

            var previous = next - 1;
            var span = channel.Times[next] - channel.Times[previous];
            // A step curve holds its value until the next key
            if (span <= 0 || channel.Interpolations[previous] == InterpolationType.Step) return Frame(channel, previous);

            var amount = (float)((time - channel.Times[previous]) / span);
            var from = Frame(channel, previous);
            var to = Frame(channel, next);
            var result = new float[from.Length];
            for (var i = 0; i < result.Length; i++)
            {
                result[i] = from[i] + (to[i] - from[i]) * amount;
            }
            return result;
        }

        private static float[] Frame(AnimationChannel channel, int index)
        {
            var frame = new float[channel.Stride];
            Array.Copy(channel.Values, index * channel.Stride, frame, 0, channel.Stride);
            return frame;
        }

        private static InterpolationType InterpolationAt(List<AnimationChannel> channels, double time)
        {
            foreach (var channel in channels)
            {
                for (var i = 0; i < channel.FrameCount; i++)
                {
                    if (Math.Abs(channel.Times[i] - time) <= 1e-6) return channel.Interpolations[i];
                }
            }
            return InterpolationType.Linear;
        }

        /// <summary>Visual-scene nodes by id and by sid: a channel targets one of these, and which of the two is
        /// the exporter's choice.</summary>
        public static Dictionary<String, node> IndexNodes(List<visual_scene> visualScenes)
        {
            var nodes = new Dictionary<String, node>(StringComparer.Ordinal);
            foreach (var scene in visualScenes ?? new List<visual_scene>())
            {
                foreach (var root in scene?.node ?? Array.Empty<node>())
                {
                    IndexNode(root, nodes);
                }
            }
            return nodes;
        }

        private static void IndexNode(node node, Dictionary<String, node> nodes)
        {
            if (node == null) return;

            if (!String.IsNullOrEmpty(node.id)) nodes[node.id] = node;
            if (!String.IsNullOrEmpty(node.sid)) nodes[node.sid] = node;

            foreach (var child in node.node1 ?? Array.Empty<node>())
            {
                IndexNode(child, nodes);
            }
        }
    }
}
