using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using QuantumBinding.Generator;
using QuantumBinding.Generator.CodeGeneration;
using QuantumBinding.Generator.ProcessingFluentApi;
using QuantumBinding.Generator.Processors;
using QuantumBinding.Generator.Utils;

namespace Adamantium.GameInput.Generator;

/// <summary>
/// Generates Adamantium.GameInput from the flat-C facade over Microsoft GameInput (native: gameinput-c-shared.dll).
/// </summary>
public class GameInputBindingGenerator : QuantumBindingGenerator
{
    private Module module;

    public override void OnSetup(BindingOptions options)
    {
        var header = @$"
            ----------------------------------------------------------------------------------------------
            <auto-generated>
            This file was autogenerated by {GeneratorName}.
            Do not edit this file manually because you will lose all your changes after the next generation.
            </auto-generated>
            ----------------------------------------------------------------------------------------------";

        var project = Path.GetFullPath(Path.Combine(SourceDirectory(), "..", "Adamantium.GameInput"));

        options.GenerateSequentialLayout = true;
        options.PodTypesAsSimpleTypes = false;
        options.DebugMode = false;

        module = Module.Create("gameinput-c-shared");
        module.FileHeader = header;
        module.GeneratorMode = GeneratorMode.Compatible;
        module.EachTypeInSeparateFile = true;
        module.CleanPreviousGeneration = true;
        module.Name = "GameInput";
        module.Files.Add(Path.Combine(project, "native", "gameinput_c.h"));
        module.Defines.Add("_WIN32");
        module.Defines.Add("_MSC_VER");
        module.ForceCallingConvention = true;
        module.CallingConvention = CallingConvention.Winapi;
        module.MethodClassName = "GameInputNative";
        module.InteropClassName = "GameInputInterop";
        module.GeneratorSpecializations = GeneratorSpecializationUtils.AllExcept(GeneratorSpecializations.Macros);
        module.OutputFileName = "Adamantium.GameInput";
        module.OutputNamespace = "Adamantium.GameInput";
        module.InteropSubNamespace = "Interop";
        module.OutputPath = Path.Combine(project, "Generated");
        module.TargetRuntime = TargetRuntime.Net8Plus;

        options.AddModule(module);
    }

    public override void OnBeforeSetupPasses(ProcessingContext context)
    {
        var api = new PostProcessingApi();
        api.Function("gameinputc_watch_gamepads")
            .WithParameterName("userData")
            .InterpretAsPointerToVoid()
            .SetParameterKind(ParameterKind.In);
        context.AddPreGeneratorPass(new PostProcessingApiPass(api), ExecutionPassKind.PerTranslationUnit);
    }

    public override void OnSetupPostProcessing(ProcessingContext context)
    {
        context.AddPreGeneratorPass(new FunctionToInstanceMethodPass(), ExecutionPassKind.PerTranslationUnit);
        context.AddPreGeneratorPass(new CheckFlagsEnumsPass(), ExecutionPassKind.PerTranslationUnit);
        context.AddPreGeneratorPass(new EnumItemsCleanupPass(), ExecutionPassKind.PerTranslationUnit);
        context.AddPreGeneratorPass(new EnumItemsRenamePass(CasePattern.PascalCase), ExecutionPassKind.PerTranslationUnit);

        var types = RenameTargets.Enum | RenameTargets.Struct | RenameTargets.StructWrapper | RenameTargets.Class |
                    RenameTargets.Delegate;
        var renameItems = new[]
        {
            new RegexRenameRunItem("^gameinputc_", string.Empty, RenameTargets.Method, true),
            new RegexRenameRunItem("^GameInputc", "GameInput", types, false),
        };
        var renameTargets = RenameTargetsUtils.AnyExcept(RenameTargets.Function | RenameTargets.Struct);
        context.AddPreGeneratorPass(new SequentialRegexRenamePass(renameItems), ExecutionPassKind.PerTranslationUnit, module);
        context.AddPreGeneratorPass(new CaseRenamePass(renameTargets, CasePattern.PascalCase), ExecutionPassKind.PerTranslationUnit, module);
    }

    private static string SourceDirectory([CallerFilePath] string path = "")
    {
        return Path.GetDirectoryName(path);
    }
}
